<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a Frontpage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Plasma Science and Fusion Energy Institute for High School Physics
Teachers Application Form Search</title>
</head>

<body>

<form BOTID="0" METHOD="POST" ACTION="Admin_copy(1).asp">
  <table BORDER="0">
    <tr>
      <td><b>*</b></td>
      <td><input TYPE="TEXT" NAME="*" VALUE="<%=Request("*")%>" size="20"></td>
    </tr>
  </table>
  <br>
  <input TYPE="Submit"><input TYPE="Reset"><!--webbot bot="SaveAsASP" CLIENTSIDE
  SuggestedExt="asp" PREVIEW=" " startspan --><!--webbot bot="SaveAsASP" endspan -->
  <p>&nbsp;</p>
</form>
<!--webbot bot="DatabaseRegionStart" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-columntypes="3,202,202,202,202,202,202,202,202,203,203,203,3,203,203,203,203,203,203,203,203,203,202,202,202,202,202"
s-dataconnection="SummerInstituteForm" b-tableformat="FALSE"
b-menuformat="FALSE" s-menuchoice="ID" s-menuvalue="ID" b-tableborder="TRUE"
b-tableexpand="TRUE" b-tableheader="TRUE" b-listlabels="FALSE"
b-listseparator="FALSE" i-ListFormat="6" b-makeform="TRUE"
s-recordsource="TeachersApplication2000"
s-displaycolumns="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-criteria="[Name] CNT {*} | [State] CNT {*} |" s-order="[Name] +"
s-sql="SELECT * FROM TeachersApplication2000 WHERE (Name LIKE '%::*::%' OR State LIKE '%::*::%') ORDER BY Name ASC"
b-procedure="FALSE" clientside SuggestedExt="asp"
s-DefaultFields="*=&amp;amp;*="
s-NoRecordsFound="Please be less specific in your search.  If you think this message is an error please email Scott @ PPPLHelp@BeginYour.com"
i-MaxRecords="1" i-GroupSize="0" BOTID="0" u-dblib="../../_fpclass/fpdblib.inc"
u-dbrgn1="../../_fpclass/fpdbrgn1.inc" u-dbrgn2="../../_fpclass/fpdbrgn2.inc"
tag="BODY"
local_preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;Database Results regions will not preview unless this page is fetched from a Web server using a web browser. The section of the page from here to the end of the Database Results region will repeat once for each record returned by the query.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;"
preview="<table border=0 width=&quot;100%&quot;><tr><td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;><font color=&quot;#000000&quot;>This is the start of a Database Results region.</font></td></tr></table>"
b-WasTableFormat="FALSE" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<%
fp_sQry="SELECT * FROM TeachersApplication2000 WHERE (Name LIKE '%::*::%' OR State LIKE '%::*::%') ORDER BY Name ASC"
fp_sDefault="*=&*="
fp_sNoRecords="Please be less specific in your search.  If you think this message is an error please email Scott @ PPPLHelp@BeginYour.com"
fp_sDataConn="SummerInstituteForm"
fp_iMaxRecords=1
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=False
fp_fMenuFormat=False
fp_sMenuChoice="ID"
fp_sMenuValue="ID"
fp_iDisplayCols=27
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan -->
  <table border="1" width="84%" bordercolor="#DDDDDD" cellspacing="0" height="609">
    <tr>
      <td width="100%" bgcolor="#EBEBEB" colspan="2" height="15">
        <p ALIGN="CENTER"><b><font SIZE="+1">Plasma Science and Fusion Energy
        Institute<br>
        for High School Physics Teachers<br>
        July 17-28, 2000<br>
        </font>APPLICATION FORM</b></p>
      </td>
    </tr>
    <tr>
      <td width="100%" bgcolor="#FFFFCC" valign="top" colspan="2" height="8">
        <p align="center"><b><font size="4">ID#</font></b><!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="ID" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"ID")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
        &nbsp;&nbsp;&nbsp;&nbsp; /&nbsp;&nbsp; <!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="Complete" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Complete&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Complete&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Complete")%><!--webbot
        bot="DatabaseResultColumn" endspan --> with the terms of the Application</p>
      </td>
    </tr>
    <tr>
      <td width="100%" bgcolor="#FFFFCC" valign="top" colspan="2" height="8"><b><font size="4">Personal
        Information</font></b></td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Name</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="Name" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Name")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>SS#</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="SocialSecurity" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SocialSecurity&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SocialSecurity&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"SocialSecurity")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="14" align="right"><b>Home
        Address</b></td>
      <td width="71%" height="14"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="Address" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Address&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Address&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Address")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="13" align="right"><b>City</b></td>
      <td width="71%" height="13"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="City" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;City&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;City&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"City")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="35%" height="21" bgcolor="#EBEBEB">
        <p align="right"><b>State:</b></p>
      </td>
      <td width="65%" height="21"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="State" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;State&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;State&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"State")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="14" align="right"><b>Zip</b></td>
      <td width="71%" height="14"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="Zip" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Zip&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Zip&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Zip")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Phone</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="Phone" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Phone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Phone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Phone")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>eMail</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="eMail" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;eMail&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;eMail&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"eMail")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><b><font size="4">Teaching
        Information</font></b></td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>School
        Name &amp; Address </b>(where presently teaching)</td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="School" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;School&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;School&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"School")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
        &nbsp;</td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>School
        Phone #&nbsp;</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="SchoolPhone" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SchoolPhone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SchoolPhone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"SchoolPhone")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Principal's
        Name</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="PrincipalName" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;PrincipalName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;PrincipalName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"PrincipalName")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b>Educational
        Information</b></font></td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
        <p><b>List in reverse chronological order the colleges/universities
        attended where a formal degree was earned.<br>
        </b>(University,<b> </b>Highest<b> </b>Degree Earned,<b> </b>Major<b>,</b>
        Award Date)&nbsp;</p>
      </td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="CollegesAttended" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CollegesAttended&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CollegesAttended&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"CollegesAttended")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" align="right" colspan="2">
        <p align="left"><font size="4"><b>Educational Experience</b></font></td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>List
        undergraduate science/math/technology courses taken.</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="UndergradCourses" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;UndergradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;UndergradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"UndergradCourses")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>List
        graduate science/math/technology courses taken.</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="GradCourses" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;GradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;GradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"GradCourses")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" align="right" colspan="2">
        <p align="left"><font size="4"><b>Professional Experience</b></font></td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Number
        of years you have taught science / math / technology classe</b>s&nbsp;<br>
        (include the sum of part-time teaching assignments.)</td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="YearsExp" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;YearsExp&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;YearsExp&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"YearsExp")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Teaching
        assignments this school year </b>(include grade levels for each</td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="TeachingAssign" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingAssign&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingAssign&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"TeachingAssign")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Anticipated
        teaching assignments next year&nbsp;</b><br>
        (if different from above):</td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="FutureTeachings" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FutureTeachings&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FutureTeachings&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"FutureTeachings")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>How
        have you advanced your professional development</b>&nbsp;<br>
        (e.g., workshops, institutes, conferences, research experience) during
        the last 3 to 5 years</td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="ProDev" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ProDev&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ProDev&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"ProDev")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19">
        <p align="right"><b>Describe your leadership activities, contributions
        to science, math or technology education </b>(in-class or out of class),<b>
        or other outstanding accomplishments during the last 3 to 5 years.</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="LeadershipActivities" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LeadershipActivities&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LeadershipActivities&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"LeadershipActivities")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19">
        <p align="right"><b>List any relevant publications that you may have.</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="Publications" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Publications&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Publications&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Publications")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19">
        <p align="right"><b>Briefly describe your teaching philosophy. Include
        how your teaching is innovative and describe your goals when teaching.
        Include a lesson plan, if available. If necessary, this can be faxed
        instead of included here</b> (609-243-2112).</td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="TeachingPhilosophy" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingPhilosophy&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingPhilosophy&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"TeachingPhilosophy")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b>Equipment
        Experience</b></font></td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>List
        scientific or electronic equipment experience and the extent of this
        experience. Have you ever worked with high voltage power supplies? Other
        electrical equipment? Vacuum pumps? Optics/Spectrometers? Lasers?</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="EquiptExperience" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;EquiptExperience&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;EquiptExperience&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"EquiptExperience")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>List
        computer hardware and software experience, your level of proficiency and
        length of experience</b></td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="CompExpierence" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CompExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CompExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"CompExpierence")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
        <p><b>4. Do you use the Internet with your students? How? Do you use
        email regularly?</b></p>
        <p>&nbsp;</td>
      <td width="71%" height="19"><!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="IntExpierence" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;IntExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;IntExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"IntExpierence")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
      </td>
    </tr>
    <tr>
      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>How
        did you learn about the Institute?</b></td>
      <td width="71%" height="19">
        <p><!--webbot bot="DatabaseResultColumn" startspan
        s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
        s-column="HowDidYouLearnAboutUs" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;HowDidYouLearnAboutUs&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;HowDidYouLearnAboutUs&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"HowDidYouLearnAboutUs")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
        </p>
      </td>
    </tr>
  </table>
<pre>&nbsp;</pre>
<pre><!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="ID" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"ID")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="Name" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Name")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="SocialSecurity" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SocialSecurity&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SocialSecurity&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"SocialSecurity")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="Address" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Address&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Address&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Address")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="Phone" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Phone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Phone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Phone")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="eMail" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;eMail&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;eMail&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"eMail")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="School" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;School&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;School&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"School")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="SchoolPhone" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SchoolPhone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SchoolPhone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"SchoolPhone")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="PrincipalName" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;PrincipalName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;PrincipalName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"PrincipalName")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="CollegesAttended" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CollegesAttended&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CollegesAttended&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"CollegesAttended")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="UndergradCourses" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;UndergradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;UndergradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"UndergradCourses")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="GradCourses" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;GradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;GradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"GradCourses")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="YearsExp" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;YearsExp&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;YearsExp&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"YearsExp")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="TeachingAssign" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingAssign&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingAssign&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"TeachingAssign")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="FutureTeachings" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FutureTeachings&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FutureTeachings&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"FutureTeachings")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="ProDev" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ProDev&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ProDev&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"ProDev")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="LeadershipActivities" b-tableformat="FALSE" b-hasHTML="FALSE"
clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LeadershipActivities&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LeadershipActivities&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"LeadershipActivities")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="Publications" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Publications&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Publications&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Publications")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="TeachingPhilosophy" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingPhilosophy&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingPhilosophy&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"TeachingPhilosophy")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="EquiptExperience" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;EquiptExperience&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;EquiptExperience&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"EquiptExperience")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="CompExpierence" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CompExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CompExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"CompExpierence")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="IntExpierence" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;IntExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;IntExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"IntExpierence")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="HowDidYouLearnAboutUs" b-tableformat="FALSE" b-hasHTML="FALSE"
clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;HowDidYouLearnAboutUs&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;HowDidYouLearnAboutUs&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"HowDidYouLearnAboutUs")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="Complete" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Complete&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Complete&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Complete")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="City" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;City&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;City&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"City")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="State" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;State&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;State&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"State")%><!--webbot
bot="DatabaseResultColumn" endspan -->
<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-column="Zip" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Zip&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Zip&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Zip")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</pre>
<!--webbot bot="DatabaseRegionEnd" startspan b-tableformat="FALSE"
b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0"
clientside tag="BODY"
local_preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;center&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;End of Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;"
preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;" --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan -->

</body>

</html>
