<%' FP_ASP ASP Automatically generated by a Frontpage Component. Do not Edit.

On Error Resume Next
Session("FP_OldCodePage") = Session.CodePage
Session("FP_OldLCID") = Session.LCID
Session.CodePage = 1252
Err.Clear

strErrorUrl = ""

If Request.ServerVariables("REQUEST_METHOD") = "POST" Then
If Request.Form("VTI-GROUP") = "0" Then
	Err.Clear

	Set fp_conn =  Server.CreateObject("ADODB.Connection")
	FP_DumpError strErrorUrl, "Cannot create connection"

	Set fp_rs = Server.CreateObject("ADODB.Recordset")
	FP_DumpError strErrorUrl, "Cannot create record set"

	fp_conn.Open Application("NUFP_ConnectionString")
	FP_DumpError strErrorUrl, "Cannot open database"

	fp_rs.Open "NUFP", fp_conn, 1, 3, 2 ' adOpenKeySet, adLockOptimistic, adCmdTable
	FP_DumpError strErrorUrl, "Cannot open record set"

	fp_rs.AddNew
	FP_DumpError strErrorUrl, "Cannot add new record set to the database"
	Dim arFormFields0(59)
	Dim arFormDBFields0(59)
	Dim arFormValues0(59)

	arFormFields0(0) = "PermState"
	arFormDBFields0(0) = "PermState"
	arFormValues0(0) = Request("PermState")
	arFormFields0(1) = "College2_major"
	arFormDBFields0(1) = "College2_Major"
	arFormValues0(1) = Request("College2_major")
	arFormFields0(2) = "ResearchExperience"
	arFormDBFields0(2) = "ResearchExperience"
	arFormValues0(2) = Request("ResearchExperience")
	arFormFields0(3) = "cad"
	arFormDBFields0(3) = "cad"
	arFormValues0(3) = Request("cad")
	arFormFields0(4) = "Preference"
	arFormDBFields0(4) = "Preference"
	arFormValues0(4) = Request("Preference")
	arFormFields0(5) = "ExpYear"
	arFormDBFields0(5) = "ExpYear"
	arFormValues0(5) = Request("ExpYear")
	arFormFields0(6) = "College3_major"
	arFormDBFields0(6) = "College3_Major"
	arFormValues0(6) = Request("College3_major")
	arFormFields0(7) = "College4_major"
	arFormDBFields0(7) = "College4_Major"
	arFormValues0(7) = Request("College4_major")
	arFormFields0(8) = "College1_Credits"
	arFormDBFields0(8) = "College1_Credits"
	arFormValues0(8) = Request("College1_Credits")
	arFormFields0(9) = "HowHear"
	arFormDBFields0(9) = "HowHeard"
	arFormValues0(9) = Request("HowHear")
	arFormFields0(10) = "Rec1Name"
	arFormDBFields0(10) = "Rec1Name"
	arFormValues0(10) = Request("Rec1Name")
	arFormFields0(11) = "CurrentCollege"
	arFormDBFields0(11) = "CurrentCollege"
	arFormValues0(11) = Request("CurrentCollege")
	arFormFields0(12) = "Rec2Name"
	arFormDBFields0(12) = "Rec2Name"
	arFormValues0(12) = Request("Rec2Name")
	arFormFields0(13) = "Major"
	arFormDBFields0(13) = "Major"
	arFormValues0(13) = Request("Major")
	arFormFields0(14) = "STExperience"
	arFormDBFields0(14) = "STExpierence"
	arFormValues0(14) = Request("STExperience")
	arFormFields0(15) = "PermAddress"
	arFormDBFields0(15) = "PermAddress"
	arFormValues0(15) = Request("PermAddress")
	arFormFields0(16) = "PermZip"
	arFormDBFields0(16) = "PermZip"
	arFormValues0(16) = Request("PermZip")
	arFormFields0(17) = "College4_College"
	arFormDBFields0(17) = "College4_College"
	arFormValues0(17) = Request("College4_College")
	arFormFields0(18) = "Accept"
	arFormDBFields0(18) = "Accept"
	arFormValues0(18) = Request("Accept")
	arFormFields0(19) = "email"
	arFormDBFields0(19) = "eMail"
	arFormValues0(19) = Request("email")
	arFormFields0(20) = "Honors"
	arFormDBFields0(20) = "Honors"
	arFormValues0(20) = Request("Honors")
	arFormFields0(21) = "phone"
	arFormDBFields0(21) = "Phone"
	arFormValues0(21) = Request("phone")
	arFormFields0(22) = "SpecialSkills"
	arFormDBFields0(22) = "SpecialSkills"
	arFormValues0(22) = Request("SpecialSkills")
	arFormFields0(23) = "City"
	arFormDBFields0(23) = "City"
	arFormValues0(23) = Request("City")
	arFormFields0(24) = "College3_College"
	arFormDBFields0(24) = "College3_College"
	arFormValues0(24) = Request("College3_College")
	arFormFields0(25) = "College4_Credits"
	arFormDBFields0(25) = "College4_Credits"
	arFormValues0(25) = Request("College4_Credits")
	arFormFields0(26) = "College1_GPA"
	arFormDBFields0(26) = "College1_GPA"
	arFormValues0(26) = Request("College1_GPA")
	arFormFields0(27) = "DAQtext"
	arFormDBFields0(27) = "DaqText"
	arFormValues0(27) = Request("DAQtext")
	arFormFields0(28) = "ProgLang"
	arFormDBFields0(28) = "ProgLang"
	arFormValues0(28) = Request("ProgLang")
	arFormFields0(29) = "College2_GPA"
	arFormDBFields0(29) = "College2_GPA"
	arFormValues0(29) = Request("College2_GPA")
	arFormFields0(30) = "Zip"
	arFormDBFields0(30) = "Zip"
	arFormValues0(30) = Request("Zip")
	arFormFields0(31) = "PermPhone"
	arFormDBFields0(31) = "PermPhone"
	arFormValues0(31) = Request("PermPhone")
	arFormFields0(32) = "PRA"
	arFormDBFields0(32) = "PRA"
	arFormValues0(32) = Request("PRA")
	arFormFields0(33) = "College3_Credits"
	arFormDBFields0(33) = "College3_Credits"
	arFormValues0(33) = Request("College3_Credits")
	arFormFields0(34) = "College3_GPA"
	arFormDBFields0(34) = "College3_GPA"
	arFormValues0(34) = Request("College3_GPA")
	arFormFields0(35) = "name"
	arFormDBFields0(35) = "Name"
	arFormValues0(35) = Request("name")
	arFormFields0(36) = "ExpMonth"
	arFormDBFields0(36) = "ExpMonth"
	arFormValues0(36) = Request("ExpMonth")
	arFormFields0(37) = "College1_Dates"
	arFormDBFields0(37) = "College1_Dates"
	arFormValues0(37) = Request("College1_Dates")
	arFormFields0(38) = "College2_College"
	arFormDBFields0(38) = "College2_College"
	arFormValues0(38) = Request("College2_College")
	arFormFields0(39) = "College4_GPA"
	arFormDBFields0(39) = "College4_GPA"
	arFormValues0(39) = Request("College4_GPA")
	arFormFields0(40) = "FrusProject"
	arFormDBFields0(40) = "FrusProject"
	arFormValues0(40) = Request("FrusProject")
	arFormFields0(41) = "College2_Dates"
	arFormDBFields0(41) = "College2_Dates"
	arFormValues0(41) = Request("College2_Dates")
	arFormFields0(42) = "sas"
	arFormDBFields0(42) = "sas"
	arFormValues0(42) = Request("sas")
	arFormFields0(43) = "daq"
	arFormDBFields0(43) = "daq"
	arFormValues0(43) = Request("daq")
	arFormFields0(44) = "Rec2eMail"
	arFormDBFields0(44) = "Rec2eMail"
	arFormValues0(44) = Request("Rec2eMail")
	arFormFields0(45) = "Address"
	arFormDBFields0(45) = "Address"
	arFormValues0(45) = Request("Address")
	arFormFields0(46) = "State"
	arFormDBFields0(46) = "State"
	arFormValues0(46) = Request("State")
	arFormFields0(47) = "Citizen"
	arFormDBFields0(47) = "Citizen"
	arFormValues0(47) = Request("Citizen")
	arFormFields0(48) = "PRACountry"
	arFormDBFields0(48) = "PRACountry"
	arFormValues0(48) = Request("PRACountry")
	arFormFields0(49) = "College3_Dates"
	arFormDBFields0(49) = "College3_Dates"
	arFormValues0(49) = Request("College3_Dates")
	arFormFields0(50) = "College4_Dates"
	arFormDBFields0(50) = "College4_Dates"
	arFormValues0(50) = Request("College4_Dates")
	arFormFields0(51) = "spr"
	arFormDBFields0(51) = "spr"
	arFormValues0(51) = Request("spr")
	arFormFields0(52) = "Rec1eMail"
	arFormDBFields0(52) = "Rec1eMail"
	arFormValues0(52) = Request("Rec1eMail")
	arFormFields0(53) = "PermCity"
	arFormDBFields0(53) = "PermCity"
	arFormValues0(53) = Request("PermCity")
	arFormFields0(54) = "College1_College"
	arFormDBFields0(54) = "College1_College"
	arFormValues0(54) = Request("College1_College")
	arFormFields0(55) = "College1_major"
	arFormDBFields0(55) = "College1_Major"
	arFormValues0(55) = Request("College1_major")
	arFormFields0(56) = "College2_Credits"
	arFormDBFields0(56) = "College2_Credits"
	arFormValues0(56) = Request("College2_Credits")
	arFormFields0(57) = "other"
	arFormDBFields0(57) = "other"
	arFormValues0(57) = Request("other")
	arFormFields0(58) = "geography"
	arFormDBFields0(58) = "geography"
	arFormValues0(58) = Request("geography")

	FP_SaveFormFields fp_rs, arFormFields0, arFormDBFields0


	fp_rs.Update
	FP_DumpError strErrorUrl, "Cannot update the database"

	fp_rs.Close
	fp_conn.Close

	Session("FP_SavedFields")=arFormFields0
	Session("FP_SavedValues")=arFormValues0
	Session.CodePage = Session("FP_OldCodePage")
	Session.LCID = Session("FP_OldLCID")
	Response.Redirect "Application2.asp"

End If
End If

Session.CodePage = Session("FP_OldCodePage")
Session.LCID = Session("FP_OldLCID")

%>
<HTML>
<HEAD>
  <META NAME="GENERATOR" CONTENT="Microsoft FrontPage 5.0">
  <TITLE>Application: National Undergraduate Fellowship Program</TITLE>
</HEAD>
<body bgcolor="#FFFFFF" text="#000000">

<!--webbot BOT="GeneratedScript" PREVIEW=" " startspan --><script Language="JavaScript" Type="text/javascript"><!--
function FrontPage_Form1_Validator(theForm)
{

  if (theForm.name.value == "")
  {
    alert("Please enter a value for the \"Name\" field.");
    theForm.name.focus();
    return (false);
  }

  if (theForm.email.value == "")
  {
    alert("Please enter a value for the \"eMail Address\" field.");
    theForm.email.focus();
    return (false);
  }

  if (theForm.Address.value == "")
  {
    alert("Please enter a value for the \"Address\" field.");
    theForm.Address.focus();
    return (false);
  }

  if (theForm.City.value == "")
  {
    alert("Please enter a value for the \"City\" field.");
    theForm.City.focus();
    return (false);
  }

  if (theForm.State.value == "")
  {
    alert("Please enter a value for the \"City\" field.");
    theForm.State.focus();
    return (false);
  }

  if (theForm.Zip.value == "")
  {
    alert("Please enter a value for the \"Postal Code\" field.");
    theForm.Zip.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.PRACountry.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Country of Citizenship\" field.");
    theForm.PRACountry.focus();
    return (false);
  }
  return (true);
}
//--></script><!--webbot BOT="GeneratedScript" endspan --><form method="POST" action="application.asp" onsubmit="return FrontPage_Form1_Validator(this)" name="FrontPage_Form1" language="JavaScript" webbot-action="--WEBBOT-SELF--">
  <!--webbot bot="SaveDatabase" suggestedext="asp" u-asp-include-url="../../_fpclass/fpdbform.inc" s-dataconnection="NUFP" s-recordsource="NUFP" u-database-url="../../fpdb/NUFPApplication.mdb" u-confirmation-url="Application2.asp" s-form-fields="PermState College2_major ResearchExperience cad Preference ExpYear College3_major College4_major College1_Credits HowHear Rec1Name CurrentCollege Rec2Name Major STExperience PermAddress PermZip College4_College Accept email Honors phone SpecialSkills City College3_College College4_Credits College1_GPA DAQtext ProgLang College2_GPA Zip PermPhone PRA College3_Credits College3_GPA name ExpMonth College1_Dates College2_College College4_GPA FrusProject College2_Dates sas daq Rec2eMail Address State Citizen PRACountry College3_Dates College4_Dates spr Rec1eMail PermCity College1_College College1_major College2_Credits other geography" s-form-dbfields="PermState College2_Major ResearchExperience cad Preference ExpYear College3_Major College4_Major College1_Credits HowHeard Rec1Name CurrentCollege Rec2Name Major STExpierence PermAddress PermZip College4_College Accept eMail Honors Phone SpecialSkills City College3_College College4_Credits College1_GPA DaqText ProgLang College2_GPA Zip PermPhone PRA College3_Credits College3_GPA Name ExpMonth College1_Dates College2_College College4_GPA FrusProject College2_Dates sas daq Rec2eMail Address State Citizen PRACountry College3_Dates College4_Dates spr Rec1eMail PermCity College1_College College1_Major College2_Credits other geography" startspan --><input TYPE="hidden" NAME="VTI-GROUP" VALUE="0"><!--#include file="../../_fpclass/fpdbform.inc"--><!--webbot bot="SaveDatabase" endspan i-checksum="43152" -->

  <div align="center">
    <center>
    <table border="1" width="84%" bordercolor="#DDDDDD" cellspacing="0" height="479">
      <tr>
        <td width="100%" bgcolor="#EBEBEB" colspan="4" height="39">


          <p ALIGN="CENTER"><a name="top"><b><font face="helvetica,arial,sans serif" size="4">National
Undergraduate Fellowship Program<br>
in Plasma Physics and Fusion Energy Sciences</font></b><br>
          <font face="helvetica,arial,sans serif" size="1">(Funded by the U.S. Department
of Energy's Office of Fusion Energy Sciences)</font><br>
          <br>
          <font face="helvetica,arial,sans serif" color="#cc0000" size="+1"><b>Application
Deadline: February 18, 2005<br>
          <br>
          </b></font></a>

 Having trouble? email the webmaster <a href="mailto:jmorgan@pppl.gov">here.</a>

          </td>
        </tr>
        <tr>
          <td width="100%" bgcolor="#FFFFCC" valign="top" colspan="4" height="16"><b><font size="4">Personal
        Information</font></b></td>
        </tr>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2"><b>Name</b></td>
          <td width="71%" height="19" colspan="2">

            <P>
            <!--webbot bot="Validation" s-display-name="Name" b-value-required="TRUE" --><INPUT NAME="name" TYPE="text" SIZE="29"></P>

          </td>
        </tr>
        <tr>
          <td width="29%" bgchttp://ippex.pppl.gov/Summer_Institute/NUFP/Application2.aspolor="#EBEBEB" valign="top" height="19" align="right" colspan="2"><b>email</b></td>
          <td width="71%" height="19" colspan="2">
            <!--webbot bot="Validation" s-display-name="eMail Address" b-value-required="TRUE" --><INPUT NAME="email" TYPE="text" SIZE="29"></td>
        </tr>
      </center>
      <tr>
        <td width="100%" bgcolor="#EBEBEB" valign="top" height="14" align="right" colspan="4">
          <p align="left"><b>Current Address</b></td>
        </tr>
        <center>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="10" align="right" colspan="2"><b>
        Address</b></td>
          <td width="71%" height="10" colspan="2">
            <!--webbot bot="Validation" s-display-name="Address" b-value-required="TRUE" --><INPUT NAME="Address" TYPE="text" SIZE="29"></td>
        </tr>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="13" align="right" colspan="2"><b>City</b></td>
          <td width="71%" height="13" colspan="2">
            <!--webbot bot="Validation" s-display-name="City" b-value-required="TRUE" --><INPUT NAME="City" TYPE="text" SIZE="29"></td>
        </tr>
        </center>
        <tr>
                <td width="35%" height="21" bgcolor="#EBEBEB" colspan="2">
                  <p align="right"><b>State:</b></p>
                </td>
          <center>
                <td width="65%" height="21" colspan="2">
                  <!--webbot bot="Validation" s-display-name="City" b-value-required="TRUE" --><INPUT NAME="State" TYPE="text" SIZE="29"></td>
              </tr>    <tr>
            <td width="29%" bgcolor="#EBEBEB" valign="top" height="14" align="right" colspan="2"><b>Zip</b></td>
            <td width="71%" height="14" colspan="2">
              <!--webbot bot="Validation" s-display-name="Postal Code" b-value-required="TRUE" --><INPUT NAME="Zip" TYPE="text" SIZE="7"></td>
          </tr>
          <tr>
            <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2"><b>Phone</b></td>
            <td width="71%" height="19" colspan="2"><font size="1"><INPUT NAME="phone" TYPE="text" SIZE="29">(i.e.
        609-555-1212)</font></td>
          </tr>
                <tr>
                  <td width="100%" bgcolor="#EBEBEB" valign="top" height="14" align="right" colspan="4">
                    <p align="left"><b>Permanent Address (if different)</b></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="10" align="right" colspan="2"><b>
        Address</b></td>
                    <td width="71%" height="10" colspan="2"><INPUT NAME="PermAddress" TYPE="text" SIZE="29"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="11" align="right" colspan="2"><b>City</b></td>
                    <td width="71%" height="11" colspan="2"><INPUT NAME="PermCity" TYPE="text" SIZE="29"></td>
                  </tr>
                  <tr>
                    <td width="35%" height="21" bgcolor="#EBEBEB" colspan="2">
                      <p align="right"><b>State:</b></p>
                    </td>
                    <td width="65%" height="21" colspan="2"><INPUT NAME="PermState" TYPE="text" SIZE="29"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="14" align="right" colspan="2"><b>Zip</b></td>
                    <td width="71%" height="14" colspan="2"><INPUT NAME="PermZip" TYPE="text" SIZE="7"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2"><b>Phone</b></td>
                    <td width="71%" height="19" colspan="2"><font size="1"><INPUT NAME="PermPhone" TYPE="text" SIZE="29">(i.e.
        609-555-1212)</font></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2"><b>U.S.
        Citizen or have U.S. Permanent Residence Status</b></td>
                    <td width="71%" height="19" colspan="2"><input type="checkbox" name="Citizen" value="Yes">
        Yes <input type="checkbox" name="Citizen" value="No"> No</td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2"><b>If
        you are a permanent resident alien in the U.S. please provide</b></td>
                    <td width="71%" height="19" colspan="2">PRA Number:<INPUT NAME="PRA" TYPE="text" SIZE="10">&nbsp;
        Country of Citizenship<!--webbot bot="Validation" s-display-name="Country of Citizenship" s-data-type="String" b-allow-letters="TRUE" b-allow-digits="TRUE" b-allow-whitespace="TRUE" --><INPUT NAME="PRACountry" TYPE="text" SIZE="7"></td>
                  </tr>
                  <tr>
                    <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="4"><font size="4"><b>Educational
        Information</b></font></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">

                      <b>College/University Currently Attending&nbsp;</b>

                    </td>
                    <td width="71%" height="19" colspan="2"><INPUT NAME="CurrentCollege" TYPE="text" SIZE="41"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">

                      <b>Major Expected/Declared</b>

                    </td>
                    <td width="71%" height="19" colspan="2"><INPUT NAME="Major" TYPE="text" SIZE="41"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">

                      <b>Expected Graduation Date<br>
(month/year)</b>

                    </td>
                    <td width="71%" height="19" colspan="2"><font face="Arial" size="2">Month</font> <select name="ExpMonth" value="01" size="1">
                        <option value="01" selected>01</option>
                        <option value="02">02</option>
                        <option value="03">03</option>
                        <option value="04">04</option>
                        <option value="05">05</option>
                        <option value="06">06</option>
                        <option value="07">07</option>
                        <option value="08">08</option>
                        <option value="09">09</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                      </select>   &nbsp;<font face="Arial" size="2">Year 20</font> <select name="ExpYear" value size="1">
                        <option value="04" selected>04</option>
                        <option value="05">05</option>
                        <option value="06">06</option>
                        <option>07</option>
                      </select></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">

                      <b>&nbsp;Transcripts requested from:</b>

                    </td>
                    <td width="71%" height="19" colspan="2">
                      <p align="center"><b><font face="Arial Narrow" color="#CC0000" size="4">Official
        transcripts of all undergraduate
        work are required.&nbsp; Please send to:</font></b><font size="2"><br>
                      <b>James Morgan<br>
        PPPL<br>
        P.O. Box 451<br>
        Princeton, NJ 08543</b>
                      </font>
                      <table border="1" width="100%" cellspacing="0" cellpadding="0" bordercolor="#DDDDDD">
                        <tr>
                          <td width="20%" align="center"><b>College</b></td>
                          <td width="20%" align="center"><b>Dates Attended</b></td>
                          <td width="20%" align="center"><b>Number of Credits</b></td>
                          <td width="20%" align="center"><b>Major</b></td>
                          <td width="20%" align="center"><b>GPA (Based on 4.0)</b></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College1_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College1_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College1_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College1_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College1_GPA" size="11"></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College2_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College2_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College2_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College2_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College2_GPA" size="11"></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College3_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College3_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College3_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College3_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College3_GPA" size="11"></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College4_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College4_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College4_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College4_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College4_GPA" size="11"></td>
                        </tr>
                      </table>
                      </td>
                    </tr>
                  </center>
                  <center>
                  </center>
                  <tr>
                    <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" align="right" colspan="4">
                      <p align="left"><font size="4"><b> Experience</b></font></td>
                    </tr>
                    <tr>
                      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">
                        <p align="right"><b>Research experience, paid or volunteer work</b></p>
                      </td>
                      <center>
                      <td width="71%" height="19" colspan="2"><textarea name="ResearchExperience" rows="5" cols="65"></textarea></td>
                      </tr>
                      <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2"><b>Academic
      Honors or Awards.&nbsp;</b></td>
                        <td width="71%" height="19" colspan="2"><textarea name="Honors" rows="3" cols="65"> </textarea></td>
                      </tr>
                      <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2"><b>In
      the sections below, indicate your proficiency in the following
      areas/instruments.<br>
      (1 = No Experience, 5 = Proficient)</b></td>
                        <td width="71%" height="19" colspan="2">
                          <table>
                            <tr vAlign="top">
                              <td width="50%" bgColor="#ffffcc"><font face="Arial" size="2"><b>Computer
            Skills</b></font></td>
                              <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">1</font></b></td>
                              <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">2</font></b></td>
                              <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">3</font></b></td>
                              <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">4</font></b></td>
                              <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">5</font></b></td>
                            </tr>
                            <tr vAlign="top">
                              <td><font face="Arial" size="2">Spreadsheets</font></td>
                              <td align="middle"><input type="radio" value="1" name="spr"></td>
                              <td align="middle"><input type="radio" value="2" name="spr"></td>
                              <td align="middle"><input type="radio" value="3" name="spr"></td>
                              <td align="middle"><input type="radio" value="4" name="spr"></td>
                              <td align="middle"><input type="radio" value="5" name="spr"></td>
                            </tr>
                            <tr vAlign="top">
                              <td><font face="Arial" size="2">Statistical Analysis Software</font></td>
                              <td align="middle"><input type="radio" value="1" name="sas"></td>
                              <td align="middle"><input type="radio" value="2" name="sas"></td>
                              <td align="middle"><input type="radio" value="3" name="sas"></td>
                              <td align="middle"><input type="radio" value="4" name="sas"></td>
                              <td align="middle"><input type="radio" value="5" name="sas"></td>
                            </tr>
                            <tr vAlign="top">
                              <td><font face="Arial" size="2">Computer Aided Design Software (CAD)</font></td>
                              <td align="middle"><input type="radio" value="1" name="cad"></td>
                              <td align="middle"><input type="radio" value="2" name="cad"></td>
                              <td align="middle"><input type="radio" value="3" name="cad"></td>
                              <td align="middle"><input type="radio" value="4" name="cad"></td>
                              <td align="middle"><input type="radio" value="5" name="cad"></td>
                            </tr>
                            <tr vAlign="top">
                              <td><font face="Arial" size="2">Data Acquisition (DAQ) Software</font></td>
                              <td align="middle"><input type="radio" value="1" name="daq"></td>
                              <td align="middle"><input type="radio" value="2" name="daq"></td>
                              <td align="middle"><input type="radio" value="3" name="daq"></td>
                              <td align="middle"><input type="radio" value="4" name="daq"></td>
                              <td align="middle"><input type="radio" value="5" name="daq"></td>
                            </tr>
                          </table>
                        </td>
                      </tr>
                      <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2"><b>List
      any DAQ programs you have used:<br>
                          </b></td>
                        <td width="71%" height="19" colspan="2"><textarea name="DAQtext" rows="4" cols="60"></textarea></td>
                      </tr>
                    </center>
                    <tr>
                      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">
                        <p align="right"><b>List any programming languages you know (e.g.. C,
      Pascal, HTML, Java, etc.):
                        </b></td>
                        <center>
                        <td width="71%" height="19" colspan="2"><textarea name="ProgLang" rows="4" cols="60"></textarea></td>
                        </tr>
                      </center>
                      <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">
                          <b>Research Project Preference</b></td>
                        <center>
                        <td width="71%" height="19" colspan="2"><select size="1" name="Preference">
                            <option value="Experimental">Experimental</option>
                    
                            <option value="Theoretical">Theoretical</option>
                            <option value="Computational/Theoretical">Computational/Theoretical</option>
                            <option value="Computational/Experimental">Computational/Experimental</option>
                            <option value="No Preference">No Preference</option>
                            <option value="Other">Other Add Below</option>
                          </select><br>
                          <textarea name="other" rows="4" cols="65"> </textarea>
                          </td>
                        </tr>
                      </center>
                       <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">
                          <b>Geographical/Site Preference</b></td>
                        <center>
                        <td width="71%" height="19" colspan="2">
                          <p>Please list the geographical area, or  laboratory site preferred. If there is no preference, please state so.
                          <b><font color="#FF0000"><u>(50 character maximum for
                          this response.&nbsp; If you get an error, shorten this
                          answer and resubmit.)</u></font></b></p>
                          <textarea name="geography" rows="4" cols="65"> </textarea>
                          </td>
                        </tr>
                      </center>
                      
                        <center>
                     	<tr>
                          <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="4"><font size="4"><b>Essays</b></font></td>
                      	</tr>
                      
                        <tr>
                          <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">
                            <b>Briefly explain why you are applying for this fellowship.&nbsp;
                          Include a description of your career goals and how
                          this program will assist you in these goals.</b></td>
                          <td width="71%" height="19" colspan="2"><textarea name="SpecialSkills" rows="4" cols="65"> </textarea></td>
                        </tr>
                        <tr>
                          <td width="50%" bgcolor="#EBEBEB" valign="top" height="19" colspan="2"><b>Describe
                            one of your most satisfying scientific challenges
                            and how you met the challenge.</b></td>
                          <td width="50%" bgcolor="#FFFFFF" valign="top" height="19" colspan="2"><textarea rows="5" name="STExperience" cols="65"></textarea></td>
                        </tr>
                     	<tr>
                          <td width="50%" bgcolor="#EBEBEB" valign="top" height="19" colspan="2">&nbsp;</td>
                          <td width="50%" bgcolor="#FFFFFF" valign="top" height="19" colspan="2">&nbsp;</td>
                      	</tr>
                      
                     	<tr>
                          <td width="50%" bgcolor="#EBEBEB" valign="top" height="19" colspan="2"><b>Describe
                            one of your most frustrating scientific challenges
                            and what you did about it.</b></td>
                          <td width="50%" bgcolor="#FFFFFF" valign="top" height="19" colspan="2"><textarea rows="5" name="FrusProject" cols="65"></textarea></td>
                      	</tr>
                      
                     	<tr>
                          <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="4"><p align="left"><font size="4"><b>Letters of
                            Recommendation</b></font></td>
                      	  </tr>
                      
                          <tr>
                            <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="4"><b><font face="geneva,arial,verdana,sans serif">List
                            two people who are familiar with your academic and research 
              capabilities.&nbsp; An email will be sent to the people 
below asking them to submit a letter of recommendation by the February 18, 2005 application
                            deadline.</font></b></td>
                      	  </tr>
                      
							</center>
                      
                      	<tr>
          					<td width="23%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
                              <p align="left"><b>&nbsp;Reference #1</b></p>
                            </td>
                      
                          <center>
          					<td width="6%" bgcolor="#EBEBEB" valign="top" height="19" align="right">&nbsp;</td>
          					<td width="25%" height="19"><b>Name</b><INPUT NAME="Rec1Name" TYPE="text" SIZE="29"></td>
          					<td width="46%" height="19"><b>Email </b><INPUT NAME="Rec1eMail" TYPE="text" SIZE="29"></td>
       					  </tr>
       					
							</center>
                      
       					<tr>
          					<td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">
                              <p align="left"><b>&nbsp;Reference #2</b></p>
                            </td>
                      
                          <center>
          					<td width="41%" height="19"><b>Name</b><INPUT NAME="Rec2Name" TYPE="text" SIZE="29"></td>
          					<td width="30%" height="19"><b>Email </b><INPUT NAME="Rec2eMail" TYPE="text" SIZE="29"></td>
       					  </tr>

							</center>
                      
                        <center>
                        <tr>
                          <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="4"><font size="4"><b>Application
        Certification</b></font></td>
                        </tr>
                        <tr>
                          <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">

                            <b>How did you hear about this program?</b></td>
                          <td width="71%" height="19" colspan="2"><textarea name="HowHear" rows="2" cols="65"></textarea></td>
                        </tr>
                        <tr>
                          <td width="100%" bgcolor="#EBEBEB" valign="top" height="19" colspan="4">
                            <p align="center"><INPUT TYPE="checkbox" NAME="Accept" VALUE=
"I Agree">&nbsp; By checking this box, I acknowledge that my application is complete and
ready for review.</p>
                            <p align="center"><INPUT NAME="Application submitted" TYPE="submit" VALUE=
"Submit" style="font-family: Arial Black; color: #FF0000; background-color: #EBEBEB"></td>
                          </tr>
                        </table>
                        </center>
                      </div>

                    </form>

                  </form>

                  <P>&nbsp;</P>

          </FORM>
        </BODY>
      </HTML>