<%' FP_ASP ASP Automatically generated by a Frontpage Component. Do not Edit.

On Error Resume Next
Session("FP_OldCodePage") = Session.CodePage
Session("FP_OldLCID") = Session.LCID
Session.CodePage = 1252
Err.Clear

strErrorUrl = ""

If Request.ServerVariables("REQUEST_METHOD") = "POST" Then
If Request.Form("VTI-GROUP") = "0" Then
	Err.Clear

	Set fp_conn =  Server.CreateObject("ADODB.Connection")
	FP_DumpError strErrorUrl, "Cannot create connection"

	Set fp_rs = Server.CreateObject("ADODB.Recordset")
	FP_DumpError strErrorUrl, "Cannot create record set"

	fp_conn.Open Application("NUFP_ConnectionString")
	FP_DumpError strErrorUrl, "Cannot open database"

	fp_rs.Open "NUFP", fp_conn, 1, 3, 2 ' adOpenKeySet, adLockOptimistic, adCmdTable
	FP_DumpError strErrorUrl, "Cannot open record set"

	fp_rs.AddNew
	FP_DumpError strErrorUrl, "Cannot add new record set to the database"
	Dim arFormFields0(55)
	Dim arFormDBFields0(55)
	Dim arFormValues0(55)

	arFormFields0(0) = "cad"
	arFormDBFields0(0) = "cad"
	arFormValues0(0) = Request("cad")
	arFormFields0(1) = "ResearchExperience"
	arFormDBFields0(1) = "ResearchExperience"
	arFormValues0(1) = Request("ResearchExperience")
	arFormFields0(2) = "College2_major"
	arFormDBFields0(2) = "College2_Major"
	arFormValues0(2) = Request("College2_major")
	arFormFields0(3) = "PermState"
	arFormDBFields0(3) = "PermState"
	arFormValues0(3) = Request("PermState")
	arFormFields0(4) = "College4_major"
	arFormDBFields0(4) = "College4_Major"
	arFormValues0(4) = Request("College4_major")
	arFormFields0(5) = "College3_major"
	arFormDBFields0(5) = "College3_Major"
	arFormValues0(5) = Request("College3_major")
	arFormFields0(6) = "ExpYear"
	arFormDBFields0(6) = "ExpYear"
	arFormValues0(6) = Request("ExpYear")
	arFormFields0(7) = "HowHear"
	arFormDBFields0(7) = "HowHeard"
	arFormValues0(7) = Request("HowHear")
	arFormFields0(8) = "College1_Credits"
	arFormDBFields0(8) = "College1_Credits"
	arFormValues0(8) = Request("College1_Credits")
	arFormFields0(9) = "CurrentCollege"
	arFormDBFields0(9) = "CurrentCollege"
	arFormValues0(9) = Request("CurrentCollege")
	arFormFields0(10) = "Major"
	arFormDBFields0(10) = "Major"
	arFormValues0(10) = Request("Major")
	arFormFields0(11) = "FrusProj"
	arFormDBFields0(11) = "FrusProject"
	arFormValues0(11) = Request("FrusProj")
	arFormFields0(12) = "PermZip"
	arFormDBFields0(12) = "PermZip"
	arFormValues0(12) = Request("PermZip")
	arFormFields0(13) = "PermAddress"
	arFormDBFields0(13) = "PermAddress"
	arFormValues0(13) = Request("PermAddress")
	arFormFields0(14) = "Accept"
	arFormDBFields0(14) = "Accept"
	arFormValues0(14) = Request("Accept")
	arFormFields0(15) = "College4_College"
	arFormDBFields0(15) = "College4_College"
	arFormValues0(15) = Request("College4_College")
	arFormFields0(16) = "Honors"
	arFormDBFields0(16) = "Honors"
	arFormValues0(16) = Request("Honors")
	arFormFields0(17) = "email"
	arFormDBFields0(17) = "eMail"
	arFormValues0(17) = Request("email")
	arFormFields0(18) = "Prefernce"
	arFormDBFields0(18) = "Preference"
	arFormValues0(18) = Request("Prefernce")
	arFormFields0(19) = "SpecialSkills"
	arFormDBFields0(19) = "SpecialSkills"
	arFormValues0(19) = Request("SpecialSkills")
	arFormFields0(20) = "phone"
	arFormDBFields0(20) = "Phone"
	arFormValues0(20) = Request("phone")
	arFormFields0(21) = "SSNumber"
	arFormDBFields0(21) = "SSNumber"
	arFormValues0(21) = Request("SSNumber")
	arFormFields0(22) = "College4_Credits"
	arFormDBFields0(22) = "College4_Credits"
	arFormValues0(22) = Request("College4_Credits")
	arFormFields0(23) = "College3_College"
	arFormDBFields0(23) = "College3_College"
	arFormValues0(23) = Request("College3_College")
	arFormFields0(24) = "City"
	arFormDBFields0(24) = "City"
	arFormValues0(24) = Request("City")
	arFormFields0(25) = "ProgLang"
	arFormDBFields0(25) = "ProgLang"
	arFormValues0(25) = Request("ProgLang")
	arFormFields0(26) = "DAQtext"
	arFormDBFields0(26) = "DaqText"
	arFormValues0(26) = Request("DAQtext")
	arFormFields0(27) = "wp"
	arFormDBFields0(27) = "wp"
	arFormValues0(27) = Request("wp")
	arFormFields0(28) = "College1_GPA"
	arFormDBFields0(28) = "College1_GPA"
	arFormValues0(28) = Request("College1_GPA")
	arFormFields0(29) = "College2_GPA"
	arFormDBFields0(29) = "College2_GPA"
	arFormValues0(29) = Request("College2_GPA")
	arFormFields0(30) = "STexperience"
	arFormDBFields0(30) = "STExpierence"
	arFormValues0(30) = Request("STexperience")
	arFormFields0(31) = "College3_GPA"
	arFormDBFields0(31) = "College3_GPA"
	arFormValues0(31) = Request("College3_GPA")
	arFormFields0(32) = "College3_Credits"
	arFormDBFields0(32) = "College3_Credits"
	arFormValues0(32) = Request("College3_Credits")
	arFormFields0(33) = "PRA"
	arFormDBFields0(33) = "PRA"
	arFormValues0(33) = Request("PRA")
	arFormFields0(34) = "PermPhone"
	arFormDBFields0(34) = "PermPhone"
	arFormValues0(34) = Request("PermPhone")
	arFormFields0(35) = "Zip"
	arFormDBFields0(35) = "Zip"
	arFormValues0(35) = Request("Zip")
	arFormFields0(36) = "College2_College"
	arFormDBFields0(36) = "College2_College"
	arFormValues0(36) = Request("College2_College")
	arFormFields0(37) = "College1_Dates"
	arFormDBFields0(37) = "College1_Dates"
	arFormValues0(37) = Request("College1_Dates")
	arFormFields0(38) = "ExpMonth"
	arFormDBFields0(38) = "ExpMonth"
	arFormValues0(38) = Request("ExpMonth")
	arFormFields0(39) = "name"
	arFormDBFields0(39) = "Name"
	arFormValues0(39) = Request("name")
	arFormFields0(40) = "daq"
	arFormDBFields0(40) = "daq"
	arFormValues0(40) = Request("daq")
	arFormFields0(41) = "sas"
	arFormDBFields0(41) = "sas"
	arFormValues0(41) = Request("sas")
	arFormFields0(42) = "College2_Dates"
	arFormDBFields0(42) = "College2_Dates"
	arFormValues0(42) = Request("College2_Dates")
	arFormFields0(43) = "ExpDay"
	arFormDBFields0(43) = "ExpDay"
	arFormValues0(43) = Request("ExpDay")
	arFormFields0(44) = "spr"
	arFormDBFields0(44) = "spr"
	arFormValues0(44) = Request("spr")
	arFormFields0(45) = "College4_Dates"
	arFormDBFields0(45) = "College4_Dates"
	arFormValues0(45) = Request("College4_Dates")
	arFormFields0(46) = "College3_Dates"
	arFormDBFields0(46) = "College3_Dates"
	arFormValues0(46) = Request("College3_Dates")
	arFormFields0(47) = "PRACountry"
	arFormDBFields0(47) = "PRACountry"
	arFormValues0(47) = Request("PRACountry")
	arFormFields0(48) = "Citizen"
	arFormDBFields0(48) = "Citizen"
	arFormValues0(48) = Request("Citizen")
	arFormFields0(49) = "State"
	arFormDBFields0(49) = "State"
	arFormValues0(49) = Request("State")
	arFormFields0(50) = "Address"
	arFormDBFields0(50) = "Address"
	arFormValues0(50) = Request("Address")
	arFormFields0(51) = "College2_Credits"
	arFormDBFields0(51) = "College2_Credits"
	arFormValues0(51) = Request("College2_Credits")
	arFormFields0(52) = "College1_major"
	arFormDBFields0(52) = "College1_Major"
	arFormValues0(52) = Request("College1_major")
	arFormFields0(53) = "College1_College"
	arFormDBFields0(53) = "College1_College"
	arFormValues0(53) = Request("College1_College")
	arFormFields0(54) = "PermCity"
	arFormDBFields0(54) = "PermCity"
	arFormValues0(54) = Request("PermCity")

	FP_SaveFormFields fp_rs, arFormFields0, arFormDBFields0


	fp_rs.Update
	FP_DumpError strErrorUrl, "Cannot update the database"

	fp_rs.Close
	fp_conn.Close

	Session("FP_SavedFields")=arFormFields0
	Session("FP_SavedValues")=arFormValues0
	Session.CodePage = Session("FP_OldCodePage")
	Session.LCID = Session("FP_OldLCID")
	Response.Redirect "ApplicationConfirm.asp"

End If
End If

Session.CodePage = Session("FP_OldCodePage")
Session.LCID = Session("FP_OldLCID")

%>
<HTML>
<HEAD>
  <META NAME="GENERATOR" CONTENT="Microsoft FrontPage 4.0">
  <TITLE>Application: National Undergraduate Fellowship Program</TITLE>
</HEAD>
<BODY>

<P ALIGN=CENTER><img alt="Princeton Plasma Physics Laboratory" src="../../title_centered.gif" width="450" height="50"></P>

<!--webbot BOT="GeneratedScript" PREVIEW=" " startspan --><script Language="JavaScript" Type="text/javascript"><!--
function FrontPage_Form1_Validator(theForm)
{

  if (theForm.name.value == "")
  {
    alert("Please enter a value for the \"Name\" field.");
    theForm.name.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.name.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Name\" field.");
    theForm.name.focus();
    return (false);
  }

  if (theForm.email.value == "")
  {
    alert("Please enter a value for the \"eMail Address\" field.");
    theForm.email.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789-@. \t\r\n\f";
  var checkStr = theForm.email.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit, whitespace and \"@.\" characters in the \"eMail Address\" field.");
    theForm.email.focus();
    return (false);
  }

  var checkOK = "0123456789-.,";
  var checkStr = theForm.SSNumber.value;
  var allValid = true;
  var validGroups = true;
  var decPoints = 0;
  var allNum = "";
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
    if (ch == ".")
    {
      allNum += ".";
      decPoints++;
    }
    else if (ch == "," && decPoints != 0)
    {
      validGroups = false;
      break;
    }
    else if (ch != ",")
      allNum += ch;
  }
  if (!allValid)
  {
    alert("Please enter only digit characters in the \"Social Security Number\" field.");
    theForm.SSNumber.focus();
    return (false);
  }

  if (decPoints > 1 || !validGroups)
  {
    alert("Please enter a valid number in the \"SSNumber\" field.");
    theForm.SSNumber.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.Address.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Address\" field.");
    theForm.Address.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.City.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"City\" field.");
    theForm.City.focus();
    return (false);
  }

  if (theForm.State.selectedIndex < 0)
  {
    alert("Please select one of the \"State\" options.");
    theForm.State.focus();
    return (false);
  }

  if (theForm.State.selectedIndex == 0)
  {
    alert("The first \"State\" option is not a valid selection.  Please choose one of the other options.");
    theForm.State.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.Zip.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Postal Code\" field.");
    theForm.Zip.focus();
    return (false);
  }

  if (theForm.phone.value == "")
  {
    alert("Please enter a value for the \"Phone Number\" field.");
    theForm.phone.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.phone.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Phone Number\" field.");
    theForm.phone.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.PermAddress.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Address\" field.");
    theForm.PermAddress.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.PermCity.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"City\" field.");
    theForm.PermCity.focus();
    return (false);
  }

  if (theForm.PermState.selectedIndex < 0)
  {
    alert("Please select one of the \"State\" options.");
    theForm.PermState.focus();
    return (false);
  }

  if (theForm.PermState.selectedIndex == 0)
  {
    alert("The first \"State\" option is not a valid selection.  Please choose one of the other options.");
    theForm.PermState.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.PermZip.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Postal Code\" field.");
    theForm.PermZip.focus();
    return (false);
  }

  if (theForm.PermPhone.value == "")
  {
    alert("Please enter a value for the \"Phone Number\" field.");
    theForm.PermPhone.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.PermPhone.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Phone Number\" field.");
    theForm.PermPhone.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.PRA.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Postal Code\" field.");
    theForm.PRA.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.PRACountry.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Postal Code\" field.");
    theForm.PRACountry.focus();
    return (false);
  }
  return (true);
}
//--></script><!--webbot BOT="GeneratedScript" endspan --><form method="POST" action="lah.asp" onsubmit="return FrontPage_Form1_Validator(this)" name="FrontPage_Form1" webbot-action="--WEBBOT-SELF--" language="JavaScript">
  <!--webbot bot="SaveDatabase" startspan SuggestedExt="asp"
  U-ASP-Include-Url="../../_fpclass/fpdbform.inc" S-DataConnection="NUFP"
  S-RecordSource="NUFP" U-Database-URL="../../fpdb/NUFPApplication.mdb"
  U-Confirmation-Url="ApplicationConfirm.asp"
  S-Form-Fields="cad ResearchExperience College2_major PermState College4_major College3_major ExpYear HowHear College1_Credits CurrentCollege Major FrusProj PermZip PermAddress Accept College4_College Honors email Prefernce SpecialSkills phone SSNumber College4_Credits College3_College City ProgLang DAQtext wp College1_GPA College2_GPA STexperience College3_GPA College3_Credits PRA PermPhone Zip College2_College College1_Dates ExpMonth name daq sas College2_Dates ExpDay spr College4_Dates College3_Dates PRACountry Citizen State Address College2_Credits College1_major College1_College PermCity"
  S-Form-DBFields="cad ResearchExperience College2_Major PermState College4_Major College3_Major ExpYear HowHeard College1_Credits CurrentCollege Major FrusProject PermZip PermAddress Accept College4_College Honors eMail Preference SpecialSkills Phone SSNumber College4_Credits College3_College City ProgLang DaqText wp College1_GPA College2_GPA STExpierence College3_GPA College3_Credits PRA PermPhone Zip College2_College College1_Dates ExpMonth Name daq sas College2_Dates ExpDay spr College4_Dates College3_Dates PRACountry Citizen State Address College2_Credits College1_Major College1_College PermCity" --><input TYPE="hidden" NAME="VTI-GROUP" VALUE="0"><!--#include file="../../_fpclass/fpdbform.inc"--><!--webbot
  bot="SaveDatabase" endspan i-checksum="43152" -->

  <div align="center">
    <center>
    <table border="1" width="84%" bordercolor="#DDDDDD" cellspacing="0" height="481">
      <tr>
        <td width="100%" bgcolor="#EBEBEB" colspan="2" height="39">


          <p ALIGN="CENTER"><a name="top"><b><font face="helvetica,arial,sans serif" size="4">National
Undergraduate Fellowship Program<br>
in Plasma Physics and Fusion Energy Sciences</font></b><br>
          <font face="helvetica,arial,sans serif" size="1">(Funded by the U.S. Department
of Energy's Office of Fusion Energy Sciences)</font><br>
          <br>
          <font face="helvetica,arial,sans serif" color="#cc0000" size="+1"><b>Application
Deadline: February 2, 2002</b></font></a>

          </td>
        </tr>
        <tr>
          <td width="100%" bgcolor="#EBEBEB" colspan="2" height="1">

            <P ALIGN=CENTER>&nbsp;</P>

          </td>
        </tr>
        <tr>
          <td width="100%" bgcolor="#FFFFCC" valign="top" colspan="2" height="16"><b><font size="4">Personal
        Information</font></b></td>
        </tr>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Name</b></td>
          <td width="71%" height="19">

            <P><!--webbot bot="Validation" S-Display-Name="Name"
            S-Data-Type="String" B-Allow-Letters="TRUE" B-Allow-Digits="TRUE"
            B-Allow-WhiteSpace="TRUE" B-Value-Required="TRUE" --><INPUT NAME="name" TYPE="text" SIZE="29"></P>

          </td>
        </tr>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>E-</b><b>Mail</b></td>
          <td width="71%" height="19"><!--webbot bot="Validation"
            S-Display-Name="eMail Address" S-Data-Type="String"
            B-Allow-Letters="TRUE" B-Allow-Digits="TRUE"
            B-Allow-WhiteSpace="TRUE" S-Allow-Other-Chars="@."
            B-Value-Required="TRUE" --><INPUT NAME="email" TYPE="text" SIZE="29"></td>
        </tr>
      </center>
      <tr>
        <td width="100%" bgcolor="#EBEBEB" valign="top" height="14" align="right" colspan="2">
          <p align="left"><b>Current Address</b></td>
        </tr>
        <center>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>SS#</b></td>
          <td width="71%" height="19"><!--webbot bot="Validation"
            S-Display-Name="Social Security Number" S-Data-Type="Number"
            S-Number-Separators=",." --><INPUT NAME="SSNumber" TYPE="text" SIZE="29"></td>
        </tr>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="10" align="right"><b>Home
        Address</b></td>
          <td width="71%" height="10"><!--webbot bot="Validation"
            S-Display-Name="Address" S-Data-Type="String" B-Allow-Letters="TRUE"
            B-Allow-Digits="TRUE" B-Allow-WhiteSpace="TRUE" --><INPUT NAME="Address" TYPE="text" SIZE="29"></td>
        </tr>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="13" align="right"><b>City</b></td>
          <td width="71%" height="13"><!--webbot bot="Validation"
            S-Display-Name="City" S-Data-Type="String" B-Allow-Letters="TRUE"
            B-Allow-Digits="TRUE" B-Allow-WhiteSpace="TRUE" --><INPUT NAME="City" TYPE="text" SIZE="29"></td>
        </tr>
        </center>
        <tr>
                <td width="35%" height="21" bgcolor="#EBEBEB">
                  <p align="right"><b>State:</b></p>
                </td>
          <center>
                <td width="65%" height="21"><!--webbot bot="Validation"
                  S-Display-Name="State" B-Value-Required="TRUE"
                  B-Disallow-First-Item="TRUE" --><select size="1" name="State">
                    <option value="" selected></option>
		
                    <option value=AL>Alabama</option>
                    <option value=AK>Alaska</option>
                    <option value=AB>Alberta</option>
                    <option value=AS>American Samoa</option>
                    <option value=AZ>Arizona</option>
                    <option value=AR>Arkansas</option>
                    <option value=AA>Armed Forces America</option>
                    <option value=AE>Armed Forces Other Areas</option>
                    <option value=AP>Armed Forces Pacific</option>
                    <option value=BC>British Columbia</option>
                    <option value=CA>California</option>
                    <option value=CO>Colorado</option>
                    <option value=CT>Connecticut</option>
                    <option value=DE>Delaware</option>
                    <option value=DC>District of Columbia</option>
                    <option value=FL>Florida</option>
                    <option value=GA>Georgia</option>
                    <option value=GU>Guam</option>
                    <option value=HI>Hawaii</option>
                    <option value=ID>Idaho</option>
                    <option value=IL>Illinois</option>
                    <option value=IN>Indiana</option>
                    <option value=IA>Iowa</option>
                    <option value=KS>Kansas</option>
                    <option value=KY>Kentucky</option>
                    <option value=LA>Louisiana</option>
                    <option value=ME>Maine</option>
                    <option value=MB>Manitoba</option>
                    <option value=MH>Marshall Islands</option>
                    <option value=MD>Maryland</option>
                    <option value=MA>Massachusetts</option>
                    <option value=MI>Michigan</option>
                    <option value=FM>Micronesia</option>
                    <option value=MN>Minnesota</option>
                    <option value=MS>Mississippi</option>
                    <option value=MO>Missouri</option>
                    <option value=MT>Montana</option>
                    <option value=NE>Nebraska</option>
                    <option value=NV>Nevada</option>
                    <option value=NB>New Brunswick</option>
                    <option value=NH>New Hampshire</option>
                    <option value=NJ>New Jersey</option>
                    <option value=NM>New Mexico</option>
                    <option value=NY>New York</option>
                    <option value=NF>Newfoundland</option>
                    <option value=NC>North Carolina</option>
                    <option value=ND>North Dakota</option>
                    <option value=MP>Northern Mariana Islands</option>
                    <option value=NT>Northwest Territories</option>
                    <option value=NS>Nova Scotia</option>
                    <option value=OH>Ohio</option>
                    <option value=OK>Oklahoma</option>
                    <option value=ON>Ontario</option>
                    <option value=OR>Oregon</option>
                    <option value=PW>Palau</option>
                    <option value=PA>Pennsylvania</option>
                    <option value=PE>Prince Edward Island</option>
                    <option value=PR>Puerto Rico</option>
                    <option value=QC>Quebec</option>
                    <option value=RI>Rhode Island</option>
                    <option value=SK>Saskatchewan</option>
                    <option value=SC>South Carolina</option>
                    <option value=SD>South Dakota</option>
                    <option value=TN>Tennessee</option>
                    <option value=TX>Texas</option>
                    <option value=UT>Utah</option>
                    <option value=VT>Vermont</option>
                    <option value=VI>Virgin Islands</option>
                    <option value=VA>Virginia</option>
                    <option value=WA>Washington</option>
                    <option value=WV>West Virginia</option>
                    <option value=WI>Wisconsin</option>
                    <option value=WY>Wyoming</option>
                    <option value=YT>Yukon</option>	                  </select></td>
              </tr>    <tr>
            <td width="29%" bgcolor="#EBEBEB" valign="top" height="14" align="right"><b>Zip</b></td>
            <td width="71%" height="14"><!--webbot bot="Validation"
              S-Display-Name="Postal Code" S-Data-Type="String"
              B-Allow-Letters="TRUE" B-Allow-Digits="TRUE"
              B-Allow-WhiteSpace="TRUE" --><INPUT NAME="Zip" TYPE="text" SIZE="7"></td>
          </tr>
          <tr>
            <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Phone</b></td>
            <td width="71%" height="19"><font size="1"><!--webbot
              bot="Validation" S-Display-Name="Phone Number"
              S-Data-Type="String" B-Allow-Letters="TRUE" B-Allow-Digits="TRUE"
              B-Allow-WhiteSpace="TRUE" B-Value-Required="TRUE" --><INPUT NAME="phone" TYPE="text" SIZE="29">(i.e.
        609-555-1212)</font></td>
          </tr>
                <tr>
                  <td width="100%" bgcolor="#EBEBEB" valign="top" height="14" align="right" colspan="2">
                    <p align="left"><b>Permanent Address</b></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="10" align="right"><b>
        Address</b></td>
                    <td width="71%" height="10"><!--webbot bot="Validation"
                      S-Display-Name="Address" S-Data-Type="String"
                      B-Allow-Letters="TRUE" B-Allow-Digits="TRUE"
                      B-Allow-WhiteSpace="TRUE" --><INPUT NAME="PermAddress" TYPE="text" SIZE="29"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="13" align="right"><b>City</b></td>
                    <td width="71%" height="13"><!--webbot bot="Validation"
                      S-Display-Name="City" S-Data-Type="String"
                      B-Allow-Letters="TRUE" B-Allow-Digits="TRUE"
                      B-Allow-WhiteSpace="TRUE" --><INPUT NAME="PermCity" TYPE="text" SIZE="29"></td>
                  </tr>
                  <tr>
                    <td width="35%" height="21" bgcolor="#EBEBEB">
                      <p align="right"><b>State:</b></p>
                    </td>
                    <td width="65%" height="21"><!--webbot bot="Validation"
                      S-Display-Name="State" B-Value-Required="TRUE"
                      B-Disallow-First-Item="TRUE" --><select size="1" name="PermState">
                        <option value="" selected></option>
		
                        <option value=AL>Alabama</option>
                        <option value=AK>Alaska</option>
                        <option value=AB>Alberta</option>
                        <option value=AS>American Samoa</option>
                        <option value=AZ>Arizona</option>
                        <option value=AR>Arkansas</option>
                        <option value=AA>Armed Forces America</option>
                        <option value=AE>Armed Forces Other Areas</option>
                        <option value=AP>Armed Forces Pacific</option>
                        <option value=BC>British Columbia</option>
                        <option value=CA>California</option>
                        <option value=CO>Colorado</option>
                        <option value=CT>Connecticut</option>
                        <option value=DE>Delaware</option>
                        <option value=DC>District of Columbia</option>
                        <option value=FL>Florida</option>
                        <option value=GA>Georgia</option>
                        <option value=GU>Guam</option>
                        <option value=HI>Hawaii</option>
                        <option value=ID>Idaho</option>
                        <option value=IL>Illinois</option>
                        <option value=IN>Indiana</option>
                        <option value=IA>Iowa</option>
                        <option value=KS>Kansas</option>
                        <option value=KY>Kentucky</option>
                        <option value=LA>Louisiana</option>
                        <option value=ME>Maine</option>
                        <option value=MB>Manitoba</option>
                        <option value=MH>Marshall Islands</option>
                        <option value=MD>Maryland</option>
                        <option value=MA>Massachusetts</option>
                        <option value=MI>Michigan</option>
                        <option value=FM>Micronesia</option>
                        <option value=MN>Minnesota</option>
                        <option value=MS>Mississippi</option>
                        <option value=MO>Missouri</option>
                        <option value=MT>Montana</option>
                        <option value=NE>Nebraska</option>
                        <option value=NV>Nevada</option>
                        <option value=NB>New Brunswick</option>
                        <option value=NH>New Hampshire</option>
                        <option value=NJ>New Jersey</option>
                        <option value=NM>New Mexico</option>
                        <option value=NY>New York</option>
                        <option value=NF>Newfoundland</option>
                        <option value=NC>North Carolina</option>
                        <option value=ND>North Dakota</option>
                        <option value=MP>Northern Mariana Islands</option>
                        <option value=NT>Northwest Territories</option>
                        <option value=NS>Nova Scotia</option>
                        <option value=OH>Ohio</option>
                        <option value=OK>Oklahoma</option>
                        <option value=ON>Ontario</option>
                        <option value=OR>Oregon</option>
                        <option value=PW>Palau</option>
                        <option value=PA>Pennsylvania</option>
                        <option value=PE>Prince Edward Island</option>
                        <option value=PR>Puerto Rico</option>
                        <option value=QC>Quebec</option>
                        <option value=RI>Rhode Island</option>
                        <option value=SK>Saskatchewan</option>
                        <option value=SC>South Carolina</option>
                        <option value=SD>South Dakota</option>
                        <option value=TN>Tennessee</option>
                        <option value=TX>Texas</option>
                        <option value=UT>Utah</option>
                        <option value=VT>Vermont</option>
                        <option value=VI>Virgin Islands</option>
                        <option value=VA>Virginia</option>
                        <option value=WA>Washington</option>
                        <option value=WV>West Virginia</option>
                        <option value=WI>Wisconsin</option>
                        <option value=WY>Wyoming</option>
                        <option value=YT>Yukon</option>	                  </select></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="14" align="right"><b>Zip</b></td>
                    <td width="71%" height="14"><!--webbot bot="Validation"
                      S-Display-Name="Postal Code" S-Data-Type="String"
                      B-Allow-Letters="TRUE" B-Allow-Digits="TRUE"
                      B-Allow-WhiteSpace="TRUE" --><INPUT NAME="PermZip" TYPE="text" SIZE="7"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Phone</b></td>
                    <td width="71%" height="19"><font size="1"><!--webbot
                      bot="Validation" S-Display-Name="Phone Number"
                      S-Data-Type="String" B-Allow-Letters="TRUE"
                      B-Allow-Digits="TRUE" B-Allow-WhiteSpace="TRUE"
                      B-Value-Required="TRUE" --><INPUT NAME="PermPhone" TYPE="text" SIZE="29">(i.e.
        609-555-1212)</font></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>U.S.
        Citizen or have U.S. Permanent Residence Status</b></td>
                    <td width="71%" height="19"><input type="checkbox" name="Citizen" value="Yes">
        Yes <input type="checkbox" name="Citizen" value="No"> No</td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>If
        you are a permanent resident alien in the U.S. please provide</b></td>
                    <td width="71%" height="19">PRA Number:<!--webbot
                      bot="Validation" S-Display-Name="Postal Code"
                      S-Data-Type="String" B-Allow-Letters="TRUE"
                      B-Allow-Digits="TRUE" B-Allow-WhiteSpace="TRUE" --><INPUT NAME="PRA" TYPE="text" SIZE="10">&nbsp;
        Country of Citizenship<!--webbot bot="Validation"
                      S-Display-Name="Postal Code" S-Data-Type="String"
                      B-Allow-Letters="TRUE" B-Allow-Digits="TRUE"
                      B-Allow-WhiteSpace="TRUE" --><INPUT NAME="PRACountry" TYPE="text" SIZE="7"></td>
                  </tr>
                  <tr>
                    <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b>Educational
        Information</b></font></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                      <b>College/University Currently Attending&nbsp;</b>

                    </td>
                    <td width="71%" height="19"><INPUT NAME="CurrentCollege" TYPE="text" SIZE="41"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                      <b>Major Expected/Declared</b>

                    </td>
                    <td width="71%" height="19"><select name="Major" size="1">
                        <option Sciences? value?Computer>Computer Sciences</option>
                        <option Bioengineering? value?Engineering>Engineering - Bioengineering</option>
                        <option value?Engineering Chemical?>Engineering - Chemical</option>
                        <option value?Engineering Civil?>Engineering - Civil</option>
                        <option value?Engineering Computer?>Engineering - Computer</option>
                        <option value?Engineering Electrical?>Engineering - Electrical</option>
                        <option value?Engineering Environmental?>Engineering - Environmental</option>
                        <option value?Engineering Industrial?>Engineering - Industrial</option>
                        <option value?Engineering Materials?>Engineering - Materials</option>
                        <option value?Engineering Mechanical?>Engineering - Mechanical</option>
                        <option value?Engineering Nuclear?>Engineering - Nuclear</option>
                        <option value?Engineering Petroleum?>Engineering - Petroleum</option>
                        <option Statistics? value?Mathematics>Mathematics/Statistics</option>
                        <option Sciences Astronomy? value?Physical>Physical Sciences -
          Astronomy</option>
                        <option Sciences value?Physical Chemistry?>Physical Sciences -
          Chemistry</option>
                        <option Sciences value?Physical Earth?>Physical Sciences - Earth
          Sciences</option>
                        <option Sciences Environmental? value?Physical>Physical Sciences -
          Environmental Sciences</option>
                        <option Sciences value?Physical Geological?>Physical Sciences -
          Geological Sciences</option>
                        <option Sciences value?Physical Oceanography?>Physical Sciences -
          Oceanography</option>
                        <option Sciences value?Physical Physics?>Physical Sciences - Physics</option>
                      </select></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                      <b>Expected Graduation Date<br>
(month-day-year)</b>

                    </td>
                    <td width="71%" height="19"><font face="Arial" size="2">Month</font> <select name="ExpMonth" value="01" size="1">
                        <option value="01" selected>01</option>
                        <option>02</option>
                        <option>03</option>
                        <option>04</option>
                        <option>05</option>
                        <option>06</option>
                        <option>07</option>
                        <option>08</option>
                        <option>09</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                      </select> &nbsp;<font face="Arial" size="2">Day</font> <select name="ExpDay" value="01" size="1">
                        <option value="01" selected>01</option>
                        <option>02</option>
                        <option>03</option>
                        <option>04</option>
                        <option>05</option>
                        <option>06</option>
                        <option>07</option>
                        <option>08</option>
                        <option>09</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                        <option>13</option>
                        <option>14</option>
                        <option>15</option>
                        <option>16</option>
                        <option>17</option>
                        <option>18</option>
                        <option>19</option>
                        <option>20</option>
                        <option>21</option>
                        <option>22</option>
                        <option>23</option>
                        <option>24</option>
                        <option>25</option>
                        <option>26</option>
                        <option>27</option>
                        <option>28</option>
                        <option>29</option>
                        <option>30</option>
                        <option>31</option>
                      </select> &nbsp;<font face="Arial" size="2">Year 20</font> <select name="ExpYear" value size="1">
                        <option selected>00</option>
                        <option>02</option>
                        <option>03</option>
                        <option>04</option>
                        <option>05</option>
                        <option>06</option>
                        <option>07</option>
                        <option>08</option>
                        <option>09</option>
                        <option>10</option>
                        <option>11</option>
                        <option>12</option>
                        <option>13</option>
                        <option>15</option>
                        <option>16</option>
                        <option>17</option>
                        <option>18</option>
                        <option>19</option>
                        <option>20</option>
                      </select></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                      <b>&nbsp;Transcripts requested from:</b>

                    </td>
                    <td width="71%" height="19">Please have transcripts of all undergraduate
        work sent by February 2, 2001 to the address given at the end of this
        application.&nbsp;
                      <table border="1" width="100%" cellspacing="0" cellpadding="0" bordercolor="#DDDDDD">
                        <tr>
                          <td width="20%" align="center"><b>College</b></td>
                          <td width="20%" align="center"><b>Dates Attended</b></td>
                          <td width="20%" align="center"><b>Number of Credits</b></td>
                          <td width="20%" align="center"><b>Major</b></td>
                          <td width="20%" align="center"><b>GPA (Based on 4.0)</b></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College1_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College1_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College1_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College1_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College1_GPA" size="11"></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College2_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College2_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College2_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College2_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College2_GPA" size="11"></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College3_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College3_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College3_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College3_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College3_GPA" size="11"></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College4_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College4_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College4_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College4_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College4_major" size="11"></td>
                        </tr>
                      </table>
                    </td>
                  </tr>
          </center>
          <center>
          </center>
          <tr>
            <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" align="right" colspan="2">
              <p align="left"><font size="4"><b> Experience</b></font></td>
            </tr>
            <tr>
              <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
                <p align="right"><b>Research experience, paid or volunteer work</b></p>
              </td>
              <center>
              <td width="71%" height="19"><textarea name="ResearchExperience" rows="5" cols="65"></textarea></td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Academic
      Honors or Awards. Enter &quot;NONE&quot; if applicable:</b></td>
                <td width="71%" height="19"><textarea name="Honors" rows="3" cols="65"> </textarea></td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>In
      the sections below, indicate your proficiency in the following
      areas/instruments.<br>
      (1 = No Experience, 5 = Proficient)</b></td>
                <td width="71%" height="19">
                  <table>
                    <tr vAlign="top">
                      <td width="50%" bgColor="#ffffcc"><font face="Arial" size="2"><b>Computer
            Skills</b></font></td>
                      <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">1</font></b></td>
                      <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">2</font></b></td>
                      <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">3</font></b></td>
                      <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">4</font></b></td>
                      <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">5</font></b></td>
                    </tr>
                    <tr vAlign="top">
                      <td><font face="Arial" size="2">Word Processing</font></td>
                      <td align="middle"><input type="radio" value="1" name="wp"></td>
                      <td align="middle"><input type="radio" value="2" name="wp"></td>
                      <td align="middle"><input type="radio" value="3" name="wp"></td>
                      <td align="middle"><input type="radio" value="4" name="wp"></td>
                      <td align="middle"><input type="radio" value="5" name="wp"></td>
                    </tr>
                    <tr vAlign="top">
                      <td><font face="Arial" size="2">Spreadsheets</font></td>
                      <td align="middle"><input type="radio" value="1" name="spr"></td>
                      <td align="middle"><input type="radio" value="2" name="spr"></td>
                      <td align="middle"><input type="radio" value="3" name="spr"></td>
                      <td align="middle"><input type="radio" value="4" name="spr"></td>
                      <td align="middle"><input type="radio" value="5" name="spr"></td>
                    </tr>
                    <tr vAlign="top">
                      <td><font face="Arial" size="2">Statistical Analysis Software</font></td>
                      <td align="middle"><input type="radio" value="1" name="sas"></td>
                      <td align="middle"><input type="radio" value="2" name="sas"></td>
                      <td align="middle"><input type="radio" value="3" name="sas"></td>
                      <td align="middle"><input type="radio" value="4" name="sas"></td>
                      <td align="middle"><input type="radio" value="5" name="sas"></td>
                    </tr>
                    <tr vAlign="top">
                      <td><font face="Arial" size="2">Computer Aided Design Software (CAD)</font></td>
                      <td align="middle"><input type="radio" value="1" name="cad"></td>
                      <td align="middle"><input type="radio" value="2" name="cad"></td>
                      <td align="middle"><input type="radio" value="3" name="cad"></td>
                      <td align="middle"><input type="radio" value="4" name="cad"></td>
                      <td align="middle"><input type="radio" value="5" name="cad"></td>
                    </tr>
                    <tr vAlign="top">
                      <td><font face="Arial" size="2">Data Acquisition (DAQ) Software</font></td>
                      <td align="middle"><input type="radio" value="1" name="daq"></td>
                      <td align="middle"><input type="radio" value="2" name="daq"></td>
                      <td align="middle"><input type="radio" value="3" name="daq"></td>
                      <td align="middle"><input type="radio" value="4" name="daq"></td>
                      <td align="middle"><input type="radio" value="5" name="daq"></td>
                    </tr>
                  </table>
                </td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>List
      any DAQ programs you may have used:<br>
                  </b></td>
                <td width="71%" height="19"><textarea name="DAQtext" rows="4" cols="60"></textarea></td>
              </tr>
            </center>
            <tr>
              <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
                <p align="right"><b>List any programming languages you know (e.g.. C,
      Pascal, HTML, Java, etc.):<br>
                <br>
                </b></td>
                <center>
                <td width="71%" height="19"><textarea name="ProgLang" rows="4" cols="60"></textarea></td>
                </tr>
              </center>
              <tr>
                <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
                  <b>Discuss any special skills you would like to exercise or develop during
      your NUF appointment.</b><font size="1"> (In answering, you may use a list
      or a paragraph format. Your answers will be read for content rather than
      writing style. You should check your spelling and grammar.)</font></td>
                <center>
                <td width="71%" height="19"><textarea name="SpecialSkills" rows="4" cols="65"> </textarea></td>
                </tr>
              </center>
              <center>
              <tr>
                <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b>Short
        Answer Questions</b></font></td>
              </tr>
              <tr>
                <td width="100%" bgcolor="#EBEBEB" valign="top" height="19" align="right" colspan="2">
                  <p align="center"><font face="Arial" size="2">Please answer <b>one </b>of
        the following questions using no more than 250 words.<i> &nbsp;<br>
                  </i></font><i> <font face="Arial" size="1"> (Your answers
        will be read for content rather than writing style. You should check
        your spelling and grammar.)</font></i></td>
                </tr>
                <tr>
                  <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>What
        was the most rewarding educational experience you have had in science
        and /or technology? Why was it so?</b></td>
                  <td width="71%" height="19"><textarea name="STexperience" rows="4" cols="65"> </textarea></td>
                </tr>
                <tr>
                  <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                    <b>Describe a frustrating project on which you worked
and how you dealt with the challenges it presented to you.</b></td>
                  <td width="71%" height="19"><textarea name="FrusProj" rows="4" cols="65"> </textarea></td>
                </tr>
                <tr>
                  <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
                    <b>Research Project Preference</b></td>
                  <td width="71%" height="19"><select size="1" name="Prefernce">
                      <option>Experimental</option>
                      <option>Computational</option>
                      <option>Theoretical</option>
                      <option>No Preference</option>
                    </select></td>
                </tr>
                <tr>
                  <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                    <b>How did you hear about this program?</b></td>
                  <td width="71%" height="19"><textarea name="HowHear" rows="1" cols="65"></textarea></td>
                </tr>
                <tr>
                  <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b>Application
        Certification</b></font></td>
                </tr>
                <tr>
                  <td width="100%" bgcolor="#EBEBEB" valign="top" height="19" colspan="2">
                    <p align="center">I certify that the information contained herein is true, complete, and
correct, and that I plan <B>to return to the classroom as a teacher for
the following school year.</B></p>
                    <p align="center"><INPUT TYPE="checkbox" NAME="Accept" VALUE=
"I Agree">By checking this box, I acknowledge that my application is complete and
ready for review.</p>
                    <p align="center"><INPUT NAME="Application submitted" TYPE="submit" VALUE=
"Submit" style="font-family: Arial Black; color: #FF0000; background-color: #EBEBEB"></td>
                  </tr>
                </table>
              </center>
              </div>

            </form>

          </form>

          <P>&nbsp;</P>

        </FORM>
      </BODY>
    </HTML>
