      <HTML>

      <head>
      <% ' FP_ASP -- ASP Automatically generated by a Frontpage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
      <meta name="GENERATOR" content="Microsoft FrontPage 5.0">
      <meta name="ProgId" content="FrontPage.Editor.Document">
      <title>Student Application</title>
      </head>

      <% If Session("PASSWORDACCESS") <> "Yes" Then %>

      <form method="POST" action="admin.asp">
        <body>

        <div align="center"><center><p>Your are not authenticated.&nbsp; Please
        login :<a href="Admin.asp">Here</a><br>
          </center></div>
        </form>
        <% Response.End %>
        <% End If %>


        <p>&nbsp;</p>

        <!--webbot bot="DatabaseRegionStart" startspan
s-columnnames="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Rec1Name,Rec1eMail,Rec2Name,Rec2eMail,Rec3Name,Rec3eMail,Timestamp,AdminNotes"
s-columntypes="3,202,202,202,202,202,202,202,202,203,203,203,202,203,203,203,203,203,203,203,203,203,202,202,202,202,202,202,202,202,202,202,202,135,203"
s-dataconnection="TeacherApplication" b-tableformat="FALSE" b-menuformat="FALSE"
s-menuchoice="ID" s-menuvalue="ID" b-tableborder="TRUE" b-tableexpand="TRUE"
b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-ListFormat="0"
b-makeform="FALSE" s-recordsource="TeachersApplication2003"
s-displaycolumns="ID,Name,SocialSecurity,Address,Phone,eMail,School,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip"
s-criteria="{ID} EQ {ID} +" s-order="[ID] +"
s-sql="SELECT * FROM TeachersApplication2000 WHERE (ID =  ::ID::) ORDER BY ID ASC"
b-procedure="FALSE" clientside SuggestedExt="asp" s-DefaultFields="ID="
s-NoRecordsFound="No records returned." i-MaxRecords="256" i-GroupSize="1"
BOTID="0" u-dblib="../../_fpclass/fpdblib.inc" u-dbrgn1="../../_fpclass/fpdbrgn1.inc"
u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="BODY"
preview="<table border=0 width=&quot;100%&quot;><tr><td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;><font color=&quot;#000000&quot;>This is the start of a Database Results region.</font></td></tr></table>" b-WasTableFormat="FALSE" b-ReplaceDatabaseRegion="FALSE" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<% if 0 then %>
<SCRIPT Language="JavaScript">
document.write("<div style='background: yellow; color: black;'>The Database Results component on this page is unable to display database content. The page must have a filename ending in '.asp', and the web must be hosted on a server that supports Active Server Pages.</div>");
</SCRIPT>
<% end if %>
<%
fp_sQry="SELECT * FROM TeachersApplication2000 WHERE (ID =  ::ID::) ORDER BY ID ASC"
fp_sDefault="ID="
fp_sNoRecords="No records returned."
fp_sDataConn="TeacherApplication"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=1
fp_fTableFormat=False
fp_fMenuFormat=False
fp_sMenuChoice="ID"
fp_sMenuValue="ID"
fp_iDisplayCols=27
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan -->
        <table border="0" width="100%" cellspacing="4">
          <tr>
            <td width="33%" bgcolor="#FFFFCC">
              <p align="center"><a href="Admin.asp"><b><font size="2">Admin Home</font></b></a></td>
              <td width="33%" bgcolor="#FFFFFF" align="center"><b><font size="2">
              See This Students<br>
              &nbsp;Application</font></b></td>
              <td width="34%" bgcolor="#FFFFCC" align="center"><a href="RecordRecommend.asp?ID=<%=FP_FieldURL(fp_rs,"ID")%>"><b><font size="2">
              See This Students<br>
              Recommendations</font></b></a></td>
            </tr>
          </table>
          <div align="center">
            <center>
            <table border="1" width="84%" bordercolor="#DDDDDD" cellspacing="0" height="597">
              <tr>
                <td width="100%" bgcolor="#F7F7F7" colspan="2" height="15">


                  <P ALIGN=CENTER><B><FONT SIZE=+1>Plasma Science and Fusion 
                  Energy Institute<br>
                  for High School Physics Teachers<br>
                  July 17-28, 2000<br>
                  </FONT>APPLICATION FORM</B></P>

                </td>
              </tr>
              <tr>
                <td width="100%" bgcolor="#FFFFCC" valign="top" colspan="2" height="4">
                  <p align="center"><b><font size="4">ID# </font></b><a href="RecordRecommend.asp?ID=<%=FP_FieldURL(fp_rs,"ID")%>">
                  <!--webbot
        bot="DatabaseResultColumn" startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="ID" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"ID")%><!--webbot
        bot="DatabaseResultColumn" endspan --></a>&nbsp;&nbsp;&nbsp;&nbsp; 
                  /&nbsp;&nbsp;
                  <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="Complete" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Complete&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"Complete")%><!--webbot
        bot="DatabaseResultColumn" endspan --> / <b>Submitted</b>: 
                  <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="Timestamp" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Timestamp&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"Timestamp")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                  </p>
                </td>
              </tr>
              <tr>
                <td width="100%" bgcolor="#FFFFCC" valign="top" colspan="2" height="8"><b><font size="4">
                Personal Information</font></b></td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b>
                Name</b></td>
                <td width="71%" height="19">

                  <!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
s-column="Name" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"Name")%><!--webbot
bot="DatabaseResultColumn" endspan -->

                </td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b>
                SS#</b></td>
                <td width="71%" height="19">
                <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="SocialSecurity" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;#ERROR#&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"SocialSecurity")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="14" align="right"><b>
                Home Address</b></td>
                <td width="71%" height="14">
                <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="Address" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Address&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"Address")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="13" align="right"><b>
                City</b></td>
                <td width="71%" height="13">
                <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="City" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;City&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"City")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>
              <tr>
                <td width="35%" height="21" bgcolor="#F7F7F7">
                  <p align="right"><b>State:</b></p>
                </td>
                <td width="65%" height="21">
                <!--webbot
                  bot="DatabaseResultColumn" startspan
                  s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
                  s-column="State" b-tableformat="FALSE" b-hasHTML="FALSE"
                  clientside
                  preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;State&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"State")%><!--webbot
                  bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>    <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="14" align="right"><b>
                Zip</b></td>
                <td width="71%" height="14">
                <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="Zip" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Zip&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"Zip")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b>
                Phone</b></td>
                <td width="71%" height="19">
                <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="Phone" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Phone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"Phone")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="11" align="right"><b>
                eMail</b></td>
                <td width="71%" height="11">
                <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="eMail" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;eMail&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"eMail")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>
              <tr>
                <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><b><font size="4">
                Teaching Information</font></b></td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b>
                School Name &amp; Address </b>(where presently teaching)</td>
                <td width="71%" height="19">

                  <!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
s-column="School" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;#ERROR#&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"School")%><!--webbot
bot="DatabaseResultColumn" endspan -->&nbsp;&nbsp;

                </td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b>
                School Phone #&nbsp;</b></td>
                <td width="71%" height="19"> 
                <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="SchoolPhone" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;#ERROR#&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"SchoolPhone")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b>
                Principal's Name</b></td>
                <td width="71%" height="19">
                <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="PrincipalName" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;PrincipalName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"PrincipalName")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>
              <tr>
                <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b>
                Educational Information</b></font></td>
              </tr>
              <tr>
                <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right">

                  <P><b>List in reverse chronological order the 
                  colleges/universities attended where a formal degree was 
                  earned.<br>
                  </b>(University,<B> </B>Highest<B> </B>Degree Earned,<B> </B>
                  Major<B>,</B> Award Date)&nbsp;</P>

                </td>
                <td width="71%" height="19">
                <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="CollegesAttended" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CollegesAttended&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"CollegesAttended")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>
              <tr>
                <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" align="right" colspan="2">
                  <p align="left"><font size="4"><b>Educational Experience </b></font></td>
                </tr>
                <tr>
                  <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b>
                  List undergraduate science/math/technology courses taken.</b></td>
                  <td width="71%" height="19">
                  <!--webbot bot="DatabaseResultColumn" startspan
      s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
      s-column="UndergradCourses" b-tableformat="FALSE" b-hasHTML="FALSE"
      clientside
      preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;UndergradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"UndergradCourses")%><!--webbot
      bot="DatabaseResultColumn" endspan -->
                  </td>
                </tr>
                <tr>
                  <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b>
                  List graduate science/math/technology courses taken.</b></td>
                  <td width="71%" height="19">
                  <!--webbot bot="DatabaseResultColumn" startspan
      s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
      s-column="GradCourses" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
      preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;GradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"GradCourses")%><!--webbot
      bot="DatabaseResultColumn" endspan -->
                  </td>
                </tr>
                <tr>
                  <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" align="right" colspan="2">
                    <p align="left"><font size="4"><b>Professional Experience</b></font></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b> 
                    Number of years you have taught science / math / technology 
                    classe</b>s&nbsp;<br>
                    (include the sum of part-time teaching assignments.)</td>
                    <td width="71%" height="19">
                    <!--webbot bot="DatabaseResultColumn" startspan
      s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
      s-column="YearsExp" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
      preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;YearsExp&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"YearsExp")%><!--webbot
      bot="DatabaseResultColumn" endspan -->
                    </td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b> 
                    Teaching assignments this school year
                      </b> (include grade levels for each</td>
                    <td width="71%" height="19">
                    <!--webbot bot="DatabaseResultColumn" startspan
      s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
      s-column="TeachingAssign" b-tableformat="FALSE" b-hasHTML="FALSE"
      clientside
      preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingAssign&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"TeachingAssign")%><!--webbot
      bot="DatabaseResultColumn" endspan -->
                    </td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b> 
                    Anticipated teaching assignments next year&nbsp;</b><br>
                    (if different from above):</td>
                    <td width="71%" height="19">
                    <!--webbot bot="DatabaseResultColumn" startspan
      s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
      s-column="FutureTeachings" b-tableformat="FALSE" b-hasHTML="FALSE"
      clientside
      preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FutureTeachings&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"FutureTeachings")%><!--webbot
      bot="DatabaseResultColumn" endspan -->
                    </td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b> 
                    How have you advanced your professional development</b>&nbsp;<br>
                    (e.g., workshops, institutes, conferences, research 
                    experience) during the last 3 to 5 years</td>
                    <td width="71%" height="19">
                    <!--webbot bot="DatabaseResultColumn" startspan
      s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
      s-column="ProDev" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
      preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ProDev&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"ProDev")%><!--webbot
      bot="DatabaseResultColumn" endspan -->
                    </td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#F7F7F7" valign="top" height="19">
                      <p align="right"><b> Describe your leadership activities, 
                      contributions to science, math or technology education </b> 
                      (in-class or out of class),<b> or other outstanding 
                      accomplishments during the last 3 to 5 years.</b></td>
                      <td width="71%" height="19">
                      <!--webbot bot="DatabaseResultColumn" startspan
      s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
      s-column="LeadershipActivities" b-tableformat="FALSE" b-hasHTML="FALSE"
      clientside
      preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LeadershipActivities&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"LeadershipActivities")%><!--webbot
      bot="DatabaseResultColumn" endspan -->
                      </td>
                    </tr>
                    <tr>
                      <td width="29%" bgcolor="#F7F7F7" valign="top" height="19">
                        <p align="right"><b> List any relevant publications that 
                        you may have.</b></td>
                        <td width="71%" height="19">
                        <!--webbot bot="DatabaseResultColumn" startspan
      s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
      s-column="Publications" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
      preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Publications&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"Publications")%><!--webbot
      bot="DatabaseResultColumn" endspan -->
                        </td>
                      </tr>
                      <tr>
                        <td width="29%" bgcolor="#F7F7F7" valign="top" height="19">
                          <p align="right"><b> Briefly describe your teaching 
                          philosophy. Include how your teaching is innovative 
                          and describe your goals when teaching. Include a 
                          lesson plan, if available. If necessary, this can be 
                          faxed instead of included here</b> (609-243-2112).</td>
                          <td width="71%" height="19">
                          <!--webbot bot="DatabaseResultColumn" startspan
      s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
      s-column="TeachingPhilosophy" b-tableformat="FALSE" b-hasHTML="FALSE"
      clientside
      preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingPhilosophy&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"TeachingPhilosophy")%><!--webbot
      bot="DatabaseResultColumn" endspan -->
                          </td>
                        </tr>
                        <tr>
                          <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b>
                          Equipment Experience</b></font></td>
                        </tr>
                        <tr>
                          <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b> 
                          List scientific or electronic equipment experience and 
                          the extent of this experience. Have you ever worked 
                          with high voltage power supplies? Other electrical 
                          equipment? Vacuum pumps? Optics/Spectrometers? Lasers?</b></td>
                          <td width="71%" height="19">
                          <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="EquiptExperience" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;EquiptExperience&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"EquiptExperience")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                          </td>
                        </tr>
                        <tr>
                          <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b> 
                          List computer hardware and software experience, your 
                          level of proficiency and length of experience</b></td>
                          <td width="71%" height="19">
                          <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="CompExpierence" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CompExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"CompExpierence")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                          </td>
                        </tr>
                        <tr>
                          <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right">

                            <P><b>4. Do you use the Internet with your students? 
                            How? Do you use email regularly?</b></P>

                            <p>&nbsp;</td>
                            <td width="71%" height="19">
                            <!--webbot bot="DatabaseResultColumn"
        startspan
        s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
        s-column="IntExpierence" b-tableformat="FALSE" b-hasHTML="FALSE"
        clientside
        preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;IntExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"IntExpierence")%><!--webbot
        bot="DatabaseResultColumn" endspan -->
                            </td>
                          </tr>
                          <tr>
                            <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b> 
                            How did you learn about the Institute?</b></td>
                            <td width="71%" height="19">

                              <P>
                              <!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
s-column="HowDidYouLearnAboutUs" b-tableformat="FALSE" b-hasHTML="FALSE"
clientside
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;HowDidYouLearnAboutUs&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"HowDidYouLearnAboutUs")%><!--webbot
bot="DatabaseResultColumn" endspan -->
                              </P>

                            </td>
                          </tr>
                          <tr>
                            <td width="29%" bgcolor="#F7F7F7" valign="top" height="19" align="right"><b>
                            Admin Notes</b></td>
                            <td width="71%" height="19">

                              <!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,School2Phone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,AdminNotes,Browser_type1"
s-column="AdminNotes" b-tableformat="FALSE" b-hasHTML="FALSE"
clientside
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;AdminNotes&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" b-makelink b-MenuFormat --><%=FP_FieldVal(fp_rs,"AdminNotes")%><!--webbot
bot="DatabaseResultColumn" endspan -->

                            </td>
                          </tr>
                        </table>
                      </center>
                    </div>
                    <form method="POST" action="http://ippex.pppl.gov/Old%20Design/Summer_Institute/Application/UpdateAdminNotes.asp">
                      <p align="center">
                                <b>Update Admin Notes</b><br>
                                <textarea rows="4" name="NewAdmin" cols="29"><%=FP_FieldHTML(fp_rs,"AdminNotes")%></textarea>
                                <p align="center">
                                <br>
                                <input type="submit" value="Submit" name="Update"></p>
                      <input type="hidden" name="Id" value="<%=Request("ID")%>">
                      </form>
                      <p>&nbsp;</p>
                      <hr>
                      <!--webbot bot="DatabaseRegionEnd" startspan b-tableformat="FALSE"
b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0"
clientside tag="BODY"
preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;" --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan -->

                    </HTML>