<%' FP_ASP ASP Automatically generated by a Frontpage Component. Do not Edit.

On Error Resume Next
Session("FP_OldCodePage") = Session.CodePage
Session("FP_OldLCID") = Session.LCID
Session.CodePage = 1252
Err.Clear

strErrorUrl = ""

If Request.ServerVariables("REQUEST_METHOD") = "POST" Then
If Request.Form("VTI-GROUP") = "0" Then
	Err.Clear

	Set fp_conn =  Server.CreateObject("ADODB.Connection")
	FP_DumpError strErrorUrl, "Cannot create connection"

	Set fp_rs = Server.CreateObject("ADODB.Recordset")
	FP_DumpError strErrorUrl, "Cannot create record set"

	fp_conn.Open Application("NUFP_ConnectionString")
	FP_DumpError strErrorUrl, "Cannot open database"

	fp_rs.Open "NUFP", fp_conn, 1, 3, 2 ' adOpenKeySet, adLockOptimistic, adCmdTable
	FP_DumpError strErrorUrl, "Cannot open record set"

	fp_rs.AddNew
	FP_DumpError strErrorUrl, "Cannot add new record set to the database"
	Dim arFormFields0(56)
	Dim arFormDBFields0(56)
	Dim arFormValues0(56)

	arFormFields0(0) = "Preference"
	arFormDBFields0(0) = "Preference"
	arFormValues0(0) = Request("Preference")
	arFormFields0(1) = "cad"
	arFormDBFields0(1) = "cad"
	arFormValues0(1) = Request("cad")
	arFormFields0(2) = "ResearchExperience"
	arFormDBFields0(2) = "ResearchExperience"
	arFormValues0(2) = Request("ResearchExperience")
	arFormFields0(3) = "College2_major"
	arFormDBFields0(3) = "College2_Major"
	arFormValues0(3) = Request("College2_major")
	arFormFields0(4) = "PermState"
	arFormDBFields0(4) = "PermState"
	arFormValues0(4) = Request("PermState")
	arFormFields0(5) = "College4_major"
	arFormDBFields0(5) = "College4_Major"
	arFormValues0(5) = Request("College4_major")
	arFormFields0(6) = "College3_major"
	arFormDBFields0(6) = "College3_Major"
	arFormValues0(6) = Request("College3_major")
	arFormFields0(7) = "ExpYear"
	arFormDBFields0(7) = "ExpYear"
	arFormValues0(7) = Request("ExpYear")
	arFormFields0(8) = "HowHear"
	arFormDBFields0(8) = "HowHeard"
	arFormValues0(8) = Request("HowHear")
	arFormFields0(9) = "College1_Credits"
	arFormDBFields0(9) = "College1_Credits"
	arFormValues0(9) = Request("College1_Credits")
	arFormFields0(10) = "CurrentCollege"
	arFormDBFields0(10) = "CurrentCollege"
	arFormValues0(10) = Request("CurrentCollege")
	arFormFields0(11) = "Major"
	arFormDBFields0(11) = "Major"
	arFormValues0(11) = Request("Major")
	arFormFields0(12) = "PermZip"
	arFormDBFields0(12) = "PermZip"
	arFormValues0(12) = Request("PermZip")
	arFormFields0(13) = "PermAddress"
	arFormDBFields0(13) = "PermAddress"
	arFormValues0(13) = Request("PermAddress")
	arFormFields0(14) = "Accept"
	arFormDBFields0(14) = "Accept"
	arFormValues0(14) = Request("Accept")
	arFormFields0(15) = "College4_College"
	arFormDBFields0(15) = "College4_College"
	arFormValues0(15) = Request("College4_College")
	arFormFields0(16) = "Honors"
	arFormDBFields0(16) = "Honors"
	arFormValues0(16) = Request("Honors")
	arFormFields0(17) = "email"
	arFormDBFields0(17) = "eMail"
	arFormValues0(17) = Request("email")
	arFormFields0(18) = "SpecialSkills"
	arFormDBFields0(18) = "SpecialSkills"
	arFormValues0(18) = Request("SpecialSkills")
	arFormFields0(19) = "phone"
	arFormDBFields0(19) = "Phone"
	arFormValues0(19) = Request("phone")
	arFormFields0(20) = "SSNumber"
	arFormDBFields0(20) = "SSNumber"
	arFormValues0(20) = Request("SSNumber")
	arFormFields0(21) = "College4_Credits"
	arFormDBFields0(21) = "College4_Credits"
	arFormValues0(21) = Request("College4_Credits")
	arFormFields0(22) = "College3_College"
	arFormDBFields0(22) = "College3_College"
	arFormValues0(22) = Request("College3_College")
	arFormFields0(23) = "City"
	arFormDBFields0(23) = "City"
	arFormValues0(23) = Request("City")
	arFormFields0(24) = "ProgLang"
	arFormDBFields0(24) = "ProgLang"
	arFormValues0(24) = Request("ProgLang")
	arFormFields0(25) = "DAQtext"
	arFormDBFields0(25) = "DaqText"
	arFormValues0(25) = Request("DAQtext")
	arFormFields0(26) = "College1_GPA"
	arFormDBFields0(26) = "College1_GPA"
	arFormValues0(26) = Request("College1_GPA")
	arFormFields0(27) = "College2_GPA"
	arFormDBFields0(27) = "College2_GPA"
	arFormValues0(27) = Request("College2_GPA")
	arFormFields0(28) = "College3_GPA"
	arFormDBFields0(28) = "College3_GPA"
	arFormValues0(28) = Request("College3_GPA")
	arFormFields0(29) = "College3_Credits"
	arFormDBFields0(29) = "College3_Credits"
	arFormValues0(29) = Request("College3_Credits")
	arFormFields0(30) = "PRA"
	arFormDBFields0(30) = "PRA"
	arFormValues0(30) = Request("PRA")
	arFormFields0(31) = "PermPhone"
	arFormDBFields0(31) = "PermPhone"
	arFormValues0(31) = Request("PermPhone")
	arFormFields0(32) = "Zip"
	arFormDBFields0(32) = "Zip"
	arFormValues0(32) = Request("Zip")
	arFormFields0(33) = "College4_GPA"
	arFormDBFields0(33) = "College4_GPA"
	arFormValues0(33) = Request("College4_GPA")
	arFormFields0(34) = "College2_College"
	arFormDBFields0(34) = "College2_College"
	arFormValues0(34) = Request("College2_College")
	arFormFields0(35) = "College1_Dates"
	arFormDBFields0(35) = "College1_Dates"
	arFormValues0(35) = Request("College1_Dates")
	arFormFields0(36) = "ExpMonth"
	arFormDBFields0(36) = "ExpMonth"
	arFormValues0(36) = Request("ExpMonth")
	arFormFields0(37) = "name"
	arFormDBFields0(37) = "Name"
	arFormValues0(37) = Request("name")
	arFormFields0(38) = "daq"
	arFormDBFields0(38) = "daq"
	arFormValues0(38) = Request("daq")
	arFormFields0(39) = "sas"
	arFormDBFields0(39) = "sas"
	arFormValues0(39) = Request("sas")
	arFormFields0(40) = "College2_Dates"
	arFormDBFields0(40) = "College2_Dates"
	arFormValues0(40) = Request("College2_Dates")
	arFormFields0(41) = "spr"
	arFormDBFields0(41) = "spr"
	arFormValues0(41) = Request("spr")
	arFormFields0(42) = "College4_Dates"
	arFormDBFields0(42) = "College4_Dates"
	arFormValues0(42) = Request("College4_Dates")
	arFormFields0(43) = "College3_Dates"
	arFormDBFields0(43) = "College3_Dates"
	arFormValues0(43) = Request("College3_Dates")
	arFormFields0(44) = "PRACountry"
	arFormDBFields0(44) = "PRACountry"
	arFormValues0(44) = Request("PRACountry")
	arFormFields0(45) = "Citizen"
	arFormDBFields0(45) = "Citizen"
	arFormValues0(45) = Request("Citizen")
	arFormFields0(46) = "State"
	arFormDBFields0(46) = "State"
	arFormValues0(46) = Request("State")
	arFormFields0(47) = "Address"
	arFormDBFields0(47) = "Address"
	arFormValues0(47) = Request("Address")
	arFormFields0(48) = "College2_Credits"
	arFormDBFields0(48) = "College2_Credits"
	arFormValues0(48) = Request("College2_Credits")
	arFormFields0(49) = "College1_major"
	arFormDBFields0(49) = "College1_Major"
	arFormValues0(49) = Request("College1_major")
	arFormFields0(50) = "College1_College"
	arFormDBFields0(50) = "College1_College"
	arFormValues0(50) = Request("College1_College")
	arFormFields0(51) = "PermCity"
	arFormDBFields0(51) = "PermCity"
	arFormValues0(51) = Request("PermCity")
	arFormFields0(52) = "Rec1Name"
	arFormDBFields0(52) = "Rec1Name"
	arFormValues0(52) = Request("Rec1Name")
	arFormFields0(53) = "Rec2Name"
	arFormDBFields0(53) = "Rec2Name"
	arFormValues0(53) = Request("Rec2Name")
	arFormFields0(54) = "Rec1eMail"
	arFormDBFields0(54) = "Rec1eMail"
	arFormValues0(54) = Request("Rec1eMail")
	arFormFields0(55) = "Rec2eMail"
	arFormDBFields0(55) = "Rec2eMail"
	arFormValues0(55) = Request("Rec2eMail")

	FP_SaveFormFields fp_rs, arFormFields0, arFormDBFields0


	fp_rs.Update
	FP_DumpError strErrorUrl, "Cannot update the database"

	fp_rs.Close
	fp_conn.Close

	Session("FP_SavedFields")=arFormFields0
	Session("FP_SavedValues")=arFormValues0
	Session.CodePage = Session("FP_OldCodePage")
	Session.LCID = Session("FP_OldLCID")
	Response.Redirect "Application2.asp"

End If
End If

Session.CodePage = Session("FP_OldCodePage")
Session.LCID = Session("FP_OldLCID")

%>
<HTML>
<HEAD>
  <META NAME="GENERATOR" CONTENT="Microsoft FrontPage 4.0">
  <TITLE>Application: National Undergraduate Fellowship Program</TITLE>
</HEAD>
<body bgcolor="#FFFFFF" text="#000000">

<!--webbot BOT="GeneratedScript" PREVIEW=" " startspan --><script Language="JavaScript" Type="text/javascript"><!--
function FrontPage_Form1_Validator(theForm)
{

  if (theForm.name.value == "")
  {
    alert("Please enter a value for the \"Name\" field.");
    theForm.name.focus();
    return (false);
  }

  if (theForm.email.value == "")
  {
    alert("Please enter a value for the \"eMail Address\" field.");
    theForm.email.focus();
    return (false);
  }

  if (theForm.Address.value == "")
  {
    alert("Please enter a value for the \"Address\" field.");
    theForm.Address.focus();
    return (false);
  }

  if (theForm.City.value == "")
  {
    alert("Please enter a value for the \"City\" field.");
    theForm.City.focus();
    return (false);
  }

  if (theForm.State.value == "")
  {
    alert("Please enter a value for the \"City\" field.");
    theForm.State.focus();
    return (false);
  }

  if (theForm.Zip.value == "")
  {
    alert("Please enter a value for the \"Postal Code\" field.");
    theForm.Zip.focus();
    return (false);
  }

  var checkOK = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzƒŠŒŽšœžŸÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ0123456789- \t\r\n\f";
  var checkStr = theForm.PRACountry.value;
  var allValid = true;
  var validGroups = true;
  for (i = 0;  i < checkStr.length;  i++)
  {
    ch = checkStr.charAt(i);
    for (j = 0;  j < checkOK.length;  j++)
      if (ch == checkOK.charAt(j))
        break;
    if (j == checkOK.length)
    {
      allValid = false;
      break;
    }
  }
  if (!allValid)
  {
    alert("Please enter only letter, digit and whitespace characters in the \"Country of Citizenship\" field.");
    theForm.PRACountry.focus();
    return (false);
  }
  return (true);
}
//--></script><!--webbot BOT="GeneratedScript" endspan --><form method="POST" action="APPLICATION_working.asp" onsubmit="return FrontPage_Form1_Validator(this)" name="FrontPage_Form1" webbot-action="--WEBBOT-SELF--" language="JavaScript">
  <!--webbot bot="SaveDatabase" startspan SuggestedExt="asp"
  U-ASP-Include-Url="../../_fpclass/fpdbform.inc" S-DataConnection="NUFP"
  S-RecordSource="NUFP" U-Database-URL="../../fpdb/NUFPApplication.mdb"
  U-Confirmation-Url="Application2.asp"
  S-Form-Fields="Preference cad ResearchExperience College2_major PermState College4_major College3_major ExpYear HowHear College1_Credits CurrentCollege Major PermZip PermAddress Accept College4_College Honors email SpecialSkills phone SSNumber College4_Credits College3_College City ProgLang DAQtext College1_GPA College2_GPA College3_GPA College3_Credits PRA PermPhone Zip College4_GPA College2_College College1_Dates ExpMonth name daq sas College2_Dates spr College4_Dates College3_Dates PRACountry Citizen State Address College2_Credits College1_major College1_College PermCity Rec1Name Rec2Name Rec1eMail Rec2eMail"
  S-Form-DBFields="Preference cad ResearchExperience College2_Major PermState College4_Major College3_Major ExpYear HowHeard College1_Credits CurrentCollege Major PermZip PermAddress Accept College4_College Honors eMail SpecialSkills Phone SSNumber College4_Credits College3_College City ProgLang DaqText College1_GPA College2_GPA College3_GPA College3_Credits PRA PermPhone Zip College4_GPA College2_College College1_Dates ExpMonth Name daq sas College2_Dates spr College4_Dates College3_Dates PRACountry Citizen State Address College2_Credits College1_Major College1_College PermCity Rec1Name Rec2Name Rec1eMail Rec2eMail" --><input TYPE="hidden" NAME="VTI-GROUP" VALUE="0"><!--#include file="../../_fpclass/fpdbform.inc"--><!--webbot
  bot="SaveDatabase" endspan i-checksum="43152" -->

  <div align="center">
    <center>
    <table border="1" width="84%" bordercolor="#DDDDDD" cellspacing="0" height="479">
      <tr>
        <td width="100%" bgcolor="#EBEBEB" colspan="2" height="39">


          <p ALIGN="CENTER"><a name="top"><b><font face="helvetica,arial,sans serif" size="4">National
Undergraduate Fellowship Program<br>
in Plasma Physics and Fusion Energy Sciences</font></b><br>
          <font face="helvetica,arial,sans serif" size="1">(Funded by the U.S. Department
of Energy's Office of Fusion Energy Sciences)</font><br>
          <br>
          <font face="helvetica,arial,sans serif" color="#cc0000" size="+1"><b>Application
Deadline: February 1, 2002<br>
          <br>
          </b></font></a>

 Having trouble? email the webmaster <a href="mailto:jmorgan@pppl.gov">here.</a>

          </td>
        </tr>
        <tr>
          <td width="100%" bgcolor="#FFFFCC" valign="top" colspan="2" height="16"><b><font size="4">Personal
        Information</font></b></td>
        </tr>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Name</b></td>
          <td width="71%" height="19">

            <P><!--webbot bot="Validation" S-Display-Name="Name"
            B-Value-Required="TRUE" --><INPUT NAME="name" TYPE="text" SIZE="29"></P>

          </td>
        </tr>
        <tr>
          <td width="29%" bgchttp://ippex.pppl.gov/Summer_Institute/NUFP/Application2.aspolor="#EBEBEB" valign="top" height="19" align="right"><b>eMail</b></td>
          <td width="71%" height="19"><!--webbot bot="Validation"
            S-Display-Name="eMail Address" B-Value-Required="TRUE" --><INPUT NAME="email" TYPE="text" SIZE="29"></td>
        </tr>
      </center>
      <tr>
        <td width="100%" bgcolor="#EBEBEB" valign="top" height="14" align="right" colspan="2">
          <p align="left"><b>Current Address</b></td>
        </tr>
        <center>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>SS#</b></td>
          <td width="71%" height="19"><INPUT NAME="SSNumber" TYPE="text" SIZE="14"></td>
        </tr>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="10" align="right"><b>
        Address</b></td>
          <td width="71%" height="10"><!--webbot bot="Validation"
            S-Display-Name="Address" B-Value-Required="TRUE" --><INPUT NAME="Address" TYPE="text" SIZE="29"></td>
        </tr>
        <tr>
          <td width="29%" bgcolor="#EBEBEB" valign="top" height="13" align="right"><b>City</b></td>
          <td width="71%" height="13"><!--webbot bot="Validation"
            S-Display-Name="City" B-Value-Required="TRUE" --><INPUT NAME="City" TYPE="text" SIZE="29"></td>
        </tr>
        </center>
        <tr>
                <td width="35%" height="21" bgcolor="#EBEBEB">
                  <p align="right"><b>State:</b></p>
                </td>
          <center>
                <td width="65%" height="21"><!--webbot bot="Validation"
                  S-Display-Name="City" B-Value-Required="TRUE" --><INPUT NAME="State" TYPE="text" SIZE="29"></td>
              </tr>    <tr>
            <td width="29%" bgcolor="#EBEBEB" valign="top" height="14" align="right"><b>Zip</b></td>
            <td width="71%" height="14"><!--webbot bot="Validation"
              S-Display-Name="Postal Code" B-Value-Required="TRUE" --><INPUT NAME="Zip" TYPE="text" SIZE="7"></td>
          </tr>
          <tr>
            <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Phone</b></td>
            <td width="71%" height="19"><font size="1"><INPUT NAME="phone" TYPE="text" SIZE="29">(i.e.
        609-555-1212)</font></td>
          </tr>
                <tr>
                  <td width="100%" bgcolor="#EBEBEB" valign="top" height="14" align="right" colspan="2">
                    <p align="left"><b>Permanent Address (if different)</b></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="10" align="right"><b>
        Address</b></td>
                    <td width="71%" height="10"><INPUT NAME="PermAddress" TYPE="text" SIZE="29"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="11" align="right"><b>City</b></td>
                    <td width="71%" height="11"><INPUT NAME="PermCity" TYPE="text" SIZE="29"></td>
                  </tr>
                  <tr>
                    <td width="35%" height="21" bgcolor="#EBEBEB">
                      <p align="right"><b>State:</b></p>
                    </td>
                    <td width="65%" height="21"><INPUT NAME="PermState" TYPE="text" SIZE="29"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="14" align="right"><b>Zip</b></td>
                    <td width="71%" height="14"><INPUT NAME="PermZip" TYPE="text" SIZE="7"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Phone</b></td>
                    <td width="71%" height="19"><font size="1"><INPUT NAME="PermPhone" TYPE="text" SIZE="29">(i.e.
        609-555-1212)</font></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>U.S.
        Citizen or have U.S. Permanent Residence Status</b></td>
                    <td width="71%" height="19"><input type="checkbox" name="Citizen" value="Yes">
        Yes <input type="checkbox" name="Citizen" value="No"> No</td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>If
        you are a permanent resident alien in the U.S. please provide</b></td>
                    <td width="71%" height="19">PRA Number:<INPUT NAME="PRA" TYPE="text" SIZE="10">&nbsp;
        Country of Citizenship<!--webbot bot="Validation"
                      S-Display-Name="Country of Citizenship"
                      S-Data-Type="String" B-Allow-Letters="TRUE"
                      B-Allow-Digits="TRUE" B-Allow-WhiteSpace="TRUE" --><INPUT NAME="PRACountry" TYPE="text" SIZE="7"></td>
                  </tr>
                  <tr>
                    <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b>Educational
        Information</b></font></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                      <b>College/University Currently Attending&nbsp;</b>

                    </td>
                    <td width="71%" height="19"><INPUT NAME="CurrentCollege" TYPE="text" SIZE="41"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                      <b>Major Expected/Declared</b>

                    </td>
                    <td width="71%" height="19"><INPUT NAME="Major" TYPE="text" SIZE="41"></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                      <b>Expected Graduation Date<br>
(month/year)</b>

                    </td>
                    <td width="71%" height="19"><font face="Arial" size="2">Month</font> <select name="ExpMonth" value="01" size="1">
                        <option value="01" selected>01</option>
                        <option value="02">02</option>
                        <option value="03">03</option>
                        <option value="04">04</option>
                        <option value="05">05</option>
                        <option value="06">06</option>
                        <option value="07">07</option>
                        <option value="08">08</option>
                        <option value="09">09</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                      </select>   &nbsp;<font face="Arial" size="2">Year 20</font> <select name="ExpYear" value size="1">
                        <option selected value="02">02</option>
                        <option value="03">03</option>
                        <option value="04">04</option>
                        <option value="05">05</option>
                      </select></td>
                  </tr>
                  <tr>
                    <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                      <b>&nbsp;Transcripts requested from:</b>

                    </td>
                    <td width="71%" height="19">
                      <p align="center"><font size="2"><font face="Arial Narrow" color="#CC0000"><b>Official
        transcripts of all undergraduate
        work are required.&nbsp; Please send to:</b></font><br>
                      <b>James Morgan<br>
        PPPL<br>
        P.O. Box 451<br>
        Princeton, NJ 08543</b>
                      </font>
                      <table border="1" width="100%" cellspacing="0" cellpadding="0" bordercolor="#DDDDDD">
                        <tr>
                          <td width="20%" align="center"><b>College</b></td>
                          <td width="20%" align="center"><b>Dates Attended</b></td>
                          <td width="20%" align="center"><b>Number of Credits</b></td>
                          <td width="20%" align="center"><b>Major</b></td>
                          <td width="20%" align="center"><b>GPA (Based on 4.0)</b></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College1_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College1_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College1_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College1_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College1_GPA" size="11"></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College2_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College2_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College2_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College2_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College2_GPA" size="11"></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College3_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College3_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College3_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College3_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College3_GPA" size="11"></td>
                        </tr>
                        <tr>
                          <td width="20%" align="center"><input type="text" name="College4_College" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College4_Dates" size="15"></td>
                          <td width="20%" align="center"><input type="text" name="College4_Credits" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College4_major" size="11"></td>
                          <td width="20%" align="center"><input type="text" name="College4_GPA" size="11"></td>
                        </tr>
                      </table>
                      </td>
                    </tr>
                  </center>
                  <center>
                  </center>
                  <tr>
                    <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" align="right" colspan="2">
                      <p align="left"><font size="4"><b> Experience</b></font></td>
                    </tr>
                    <tr>
                      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
                        <p align="right"><b>Research experience, paid or volunteer work</b></p>
                      </td>
                      <center>
                      <td width="71%" height="19"><textarea name="ResearchExperience" rows="5" cols="65"></textarea></td>
                      </tr>
                      <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Academic
      Honors or Awards.&nbsp;</b></td>
                        <td width="71%" height="19"><textarea name="Honors" rows="3" cols="65"> </textarea></td>
                      </tr>
                      <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>In
      the sections below, indicate your proficiency in the following
      areas/instruments.<br>
      (1 = No Experience, 5 = Proficient)</b></td>
                        <td width="71%" height="19">
                          <table>
                            <tr vAlign="top">
                              <td width="50%" bgColor="#ffffcc"><font face="Arial" size="2"><b>Computer
            Skills</b></font></td>
                              <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">1</font></b></td>
                              <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">2</font></b></td>
                              <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">3</font></b></td>
                              <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">4</font></b></td>
                              <td align="middle" width="10%" bgColor="#ffffcc"><b><font face="Arial" size="2">5</font></b></td>
                            </tr>
                            <tr vAlign="top">
                              <td><font face="Arial" size="2">Spreadsheets</font></td>
                              <td align="middle"><input type="radio" value="1" name="spr"></td>
                              <td align="middle"><input type="radio" value="2" name="spr"></td>
                              <td align="middle"><input type="radio" value="3" name="spr"></td>
                              <td align="middle"><input type="radio" value="4" name="spr"></td>
                              <td align="middle"><input type="radio" value="5" name="spr"></td>
                            </tr>
                            <tr vAlign="top">
                              <td><font face="Arial" size="2">Statistical Analysis Software</font></td>
                              <td align="middle"><input type="radio" value="1" name="sas"></td>
                              <td align="middle"><input type="radio" value="2" name="sas"></td>
                              <td align="middle"><input type="radio" value="3" name="sas"></td>
                              <td align="middle"><input type="radio" value="4" name="sas"></td>
                              <td align="middle"><input type="radio" value="5" name="sas"></td>
                            </tr>
                            <tr vAlign="top">
                              <td><font face="Arial" size="2">Computer Aided Design Software (CAD)</font></td>
                              <td align="middle"><input type="radio" value="1" name="cad"></td>
                              <td align="middle"><input type="radio" value="2" name="cad"></td>
                              <td align="middle"><input type="radio" value="3" name="cad"></td>
                              <td align="middle"><input type="radio" value="4" name="cad"></td>
                              <td align="middle"><input type="radio" value="5" name="cad"></td>
                            </tr>
                            <tr vAlign="top">
                              <td><font face="Arial" size="2">Data Acquisition (DAQ) Software</font></td>
                              <td align="middle"><input type="radio" value="1" name="daq"></td>
                              <td align="middle"><input type="radio" value="2" name="daq"></td>
                              <td align="middle"><input type="radio" value="3" name="daq"></td>
                              <td align="middle"><input type="radio" value="4" name="daq"></td>
                              <td align="middle"><input type="radio" value="5" name="daq"></td>
                            </tr>
                          </table>
                        </td>
                      </tr>
                      <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>List
      any DAQ programs you have used:<br>
                          </b></td>
                        <td width="71%" height="19"><textarea name="DAQtext" rows="4" cols="60"></textarea></td>
                      </tr>
                    </center>
                    <tr>
                      <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
                        <p align="right"><b>List any programming languages you know (e.g.. C,
      Pascal, HTML, Java, etc.):
                        </b></td>
                        <center>
                        <td width="71%" height="19"><textarea name="ProgLang" rows="4" cols="60"></textarea></td>
                        </tr>
                      </center>
                      <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
                          <b>Briefly explain why you are applying for this fellowship</b></td>
                        <td width="71%" height="19"><textarea name="SpecialSkills" rows="4" cols="65"> </textarea></td>
                      </tr>
                      <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">
                          <b>Research Project Preference</b></td>
                        <center>
                        <td width="71%" height="19"><select size="1" name="Preference">
                            <option value="Experimental">Experimental</option>
                            <option value="Computational">Computational</option>
                            <option value="Theoretical">Theoretical</option>
                            <option value="No Preference">No Preference</option>
                          </select></td>
                        </tr>
                      </center>
                      
                        <center>
                     	<tr>
                          <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b>Letters of Reccomendation</b></font></td>
                      	</tr>
                      
                        <tr>
                          <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b><font face="geneva,arial,verdana,sans serif" size="2"><b>Please have two people who are familiar with your academic and research 
              capabilities submit letters of recommendation by the February 28, 
              2001 application deadline. An email will be sent to the people 
below asking them to submit a letter of recommendation.</b></font></b></font></td>
                      	</tr>
                      
                      	<tr>
          					<td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Name of Reference 1</b></td>
          					<td width="71%" height="19"><INPUT NAME="Rec1Name" TYPE="text" SIZE="29"></td>
       					</tr>
       					
       					<tr>
          					<td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Email of Reference 1</b></td>
          					<td width="71%" height="19"><INPUT NAME="Rec1eMail" TYPE="text" SIZE="29"></td>
       					</tr>
       					
       					<tr>
          					<td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Name of Reference 2</b></td>
          					<td width="71%" height="19"><INPUT NAME="Rec2Name" TYPE="text" SIZE="29"></td>
       					</tr>

       					<tr>
          					<td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right"><b>Email of Reference 2</b></td>
          					<td width="71%" height="19"><INPUT NAME="Rec2eMail" TYPE="text" SIZE="29"></td>
       					</tr>
       					
							</center>
                      
                      <center>
                      <tr>
                        <td width="100%" bgcolor="#FFFFCC" valign="top" height="19" colspan="2"><font size="4"><b>Application
        Certification</b></font></td>
                      </tr>
                      <tr>
                        <td width="29%" bgcolor="#EBEBEB" valign="top" height="19" align="right">

                          <b>How did you hear about this program?</b></td>
                        <td width="71%" height="19"><textarea name="HowHear" rows="2" cols="65"></textarea></td>
                      </tr>
                      <tr>
                        <td width="100%" bgcolor="#EBEBEB" valign="top" height="19" colspan="2">
                          <p align="center"><INPUT TYPE="checkbox" NAME="Accept" VALUE=
"I Agree">&nbsp; By checking this box, I acknowledge that my application is complete and
ready for review.</p>
                          <p align="center"><INPUT NAME="Application submitted" TYPE="submit" VALUE=
"Submit" style="font-family: Arial Black; color: #FF0000; background-color: #EBEBEB"></td>
                        </tr>
                      </table>
                      </center>
                    </div>

                  </form>

          </form>

          <P>&nbsp;</P>

        </FORM>
      </BODY>
    </HTML>








