<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a Frontpage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Posted Recomendations</title>
</head>

<body>

<!--webbot bot="DatabaseRegionStart" startspan
s-columnnames="ID,Name,email,Recommendation" s-columntypes="3,203,203,203"
s-dataconnection="TeacherApplication" b-tableformat="FALSE" b-menuformat="FALSE"
s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="TRUE"
b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-ListFormat="0"
b-makeform="FALSE" s-recordsource="Recommendations"
s-displaycolumns="ID,Name,email,Recommendation" s-criteria="{ID} EQ { } +"
s-criteria="{ID} EQ {ID} +" s-order="[ID] +"
s-sql="SELECT * FROM Recommendations WHERE (ID =  ::ID::) ORDER BY ID ASC"
b-procedure="FALSE" clientside SuggestedExt="asp" s-DefaultFields=" ="
s-NoRecordsFound="No records returned." i-MaxRecords="256" i-GroupSize="0"
BOTID="0" u-dblib="../../_fpclass/fpdblib.inc" u-dbrgn1="../../_fpclass/fpdbrgn1.inc"
u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="BODY"
local_preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;Database Results regions will not preview unless this page is fetched from a Web server using a web browser. The section of the page from here to the end of the Database Results region will repeat once for each record returned by the query.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;"
preview="<table border=0 width=&quot;100%&quot;><tr><td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;><font color=&quot;#000000&quot;>This is the start of a Database Results region.</font></td></tr></table>" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<%
fp_sQry="SELECT * FROM Recommendations WHERE (ID =  ::ID::) ORDER BY ID ASC"
fp_sDefault=" ="
fp_sNoRecords="No records returned."
fp_sDataConn="TeacherApplication"
fp_iMaxRecords=256
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=False
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_iDisplayCols=4
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan -->
<table border="0" width="100%" cellspacing="4">
  <tr>
    <td width="33%" bgcolor="#FFFFCC">
      <p align="center"><a href="Admin.asp">Admin Home</a></td>
    <td width="33%" bgcolor="#FFFFCC" align="center"><a href="record.asp?ID=<%=FP_FieldURL(fp_rs,"ID")%>">See
      This Students<br>
      &nbsp;Application</a></td>
    <td width="34%" bgcolor="#FFFFFF" align="center"><b>See This Students<br>
      Recommendations</b></td>
  </tr>
</table>
<table border="1" width="100%" bordercolor="#EAEAEA" cellspacing="0" cellpadding="3" height="78">
  <tr>
    <td width="100%" colspan="2" height="16">
      <p align="center"><font size="4"><b>Letter of Recommendation</b></font></td>
  </tr>
  <tr>
    <td width="50%" height="19">Written By:&nbsp; <!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,email,Recommendation" s-column="Name"
b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Name")%><!--webbot
bot="DatabaseResultColumn" endspan --> <font size="1">(<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,email,Recommendation" s-column="email"
b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;email&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;email&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"email")%><!--webbot
bot="DatabaseResultColumn" endspan -->)</font></td>
    <td width="50%" height="19">
      <p align="center">Student ID: <!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,email,Recommendation" s-column="ID" b-tableformat="FALSE"
b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"ID")%><!--webbot
bot="DatabaseResultColumn" endspan -->
    </td>
  </tr>
  <tr>
    <td width="100%" colspan="2" height="19"><!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,email,Recommendation" s-column="Recommendation"
b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Recommendation&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Recommendation&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Recommendation")%><!--webbot
bot="DatabaseResultColumn" endspan -->
    </td>
  </tr>
</table>
<p>&nbsp;</p>
<hr size="3" color="#000000">
<!--webbot bot="DatabaseRegionEnd" startspan b-tableformat="FALSE"
b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc" i-groupsize="0"
clientside tag="BODY"
local_preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;center&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;End of Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;"
preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;" --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan -->

</body>

</html>
