<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a Frontpage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>NUF Administration Page</title>
</head>

<body>
<%@ LANGUAGE="VBSCRIPT" %>
<% Response.Buffer = True %>
<% STATUS = Request("STATUS") %>
<% PASSWORD = Request("PASSWORD") %>
<% If STATUS = "CHECKEM" Then %>
      <% If PASSWORD = "NUF2002" THEN %>
            <% Session("PASSWORDACCESS") = "Yes" %>
      <% End If %>
<% End If %>

<% If Session("PASSWORDACCESS") <> "Yes" Then %>

      <form method="POST" action="Admin_copy(2).asp">
        <div align="center"><center><p><b><font size="5">National Undergraduate
          Fellowship Program&nbsp;</font></b></p>
          </center></div>
        <div align="center"><center><p><b><font size="5">Administration Page</font></b></p>
          </center></div>
        <div align="center"><center><p><input type="password" name="PASSWORD" size="10"><br>
          <input type="hidden" value="CHECKEM" Name="STATUS" >
          <input type="submit" value="Login"></p>
          </center></div>
      </form>
     <% Response.End %>
<% End If %>

<table border="0" cellspacing="0" cellpadding="0" height="1">
  <tr>
    <td width="132" align="center" rowspan="2" valign="top" height="1">
      <p align="left">
      </td>
      <td width="727" align="center" height="1">
        <font size="5">Submitted NUF Applications&nbsp;</font></td>
    </tr>
    <tr>
      <td width="727" align="center" height="261" valign="top">
  &nbsp;
        <div align="center">
          <center>
          <table width="50%" border="1" cellspacing="00" cellpadding="0" bordercolor="#000000">
            <thead>
              <tr>
                <td><b>ID</b></td>
                <td><b>Name</b></td>
              </tr>
            </thead>
            <tbody>
              <!--webbot bot="DatabaseRegionStart" startspan
        s-columnnames="ID,Name,eMail,SSNumber,Address,City,State,Zip,Phone,PermAddress,PermCity,PermState,PermZip,PermPhone,Citizen,PRA,PRACountry,CurrentCollege,Major,ExpMonth,ExpDay,ExpYear,College1_College,College1_Dates,College1_Credits,College1_Major,College1_GPA,College2_College,College2_Dates,College2_Credits,College2_Major,College2_GPA,College3_College,College3_Dates,College3_Credits,College3_Major,College3_GPA,College4_College,College4_Dates,College4_Credits,College4_Major,College4_GPA,ResearchExperience,Honors,wp,spr,sas,cad,daq,DaqText,ProgLang,SpecialSkills,Preference,STExpierence,FrusProject,HowHeard,Accept"
        s-columntypes="3,202,202,202,202,202,202,202,202,202,202,202,202,202,11,202,202,202,202,202,202,202,202,202,3,202,3,202,202,3,202,3,202,202,3,202,3,202,202,3,202,3,202,202,202,202,202,202,202,202,202,202,202,202,202,202,11"
        s-dataconnection="NUFP" b-tableformat="TRUE" b-menuformat="FALSE"
        s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="TRUE"
        b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE"
        i-ListFormat="0" b-makeform="TRUE" s-recordsource="NUFP"
        s-displaycolumns="ID,Name" s-criteria s-order s-sql="SELECT * FROM NUFP"
        b-procedure="FALSE" clientside SuggestedExt="asp" s-DefaultFields
        s-NoRecordsFound="Please be less specific in your search.  If you think this message is an error please email Scott @ PPPLHelp@BeginYour.com"
        i-MaxRecords="25" i-GroupSize="25" BOTID="0"
        u-dblib="../../_fpclass/fpdblib.inc"
        u-dbrgn1="../../_fpclass/fpdbrgn1.inc"
        u-dbrgn2="../../_fpclass/fpdbrgn2.inc" tag="TBODY"
        local_preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;Database Results regions will not preview unless this page is fetched from a Web server with a web browser. The following table row will repeat once for every record returned by the query.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;"
        preview="<tr><td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;><font color=&quot;#000000&quot;>This is the start of a Database Results region.</font></td></tr>" --><!--#include file="../../_fpclass/fpdblib.inc"-->
<%
fp_sQry="SELECT * FROM NUFP"
fp_sDefault=""
fp_sNoRecords="<tr><td colspan=2 align=left width=""100%"">Please be less specific in your search.  If you think this message is an error please email Scott @ PPPLHelp@BeginYour.com</td></tr>"
fp_sDataConn="NUFP"
fp_iMaxRecords=25
fp_iCommandType=1
fp_iPageSize=25
fp_fTableFormat=True
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_iDisplayCols=2
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan -->
              <tr>
                <td><a href="record.asp?ID=<%=FP_FieldURL(fp_rs,"ID")%>"><!--webbot
            bot="DatabaseResultColumn" startspan
            s-columnnames="ID,Name,eMail,SSNumber,Address,City,State,Zip,Phone,PermAddress,PermCity,PermState,PermZip,PermPhone,Citizen,PRA,PRACountry,CurrentCollege,Major,ExpMonth,ExpDay,ExpYear,College1_College,College1_Dates,College1_Credits,College1_Major,College1_GPA,College2_College,College2_Dates,College2_Credits,College2_Major,College2_GPA,College3_College,College3_Dates,College3_Credits,College3_Major,College3_GPA,College4_College,College4_Dates,College4_Credits,College4_Major,College4_GPA,ResearchExperience,Honors,wp,spr,sas,cad,daq,DaqText,ProgLang,SpecialSkills,Preference,STExpierence,FrusProject,HowHeard,Accept"
            s-column="ID" b-tableformat="TRUE" b-hasHTML="FALSE" clientside
            local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
            preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"ID")%><!--webbot
            bot="DatabaseResultColumn" endspan -->
                  </a></td>
                <td><!--webbot bot="DatabaseResultColumn" startspan
            s-columnnames="ID,Name,eMail,SSNumber,Address,City,State,Zip,Phone,PermAddress,PermCity,PermState,PermZip,PermPhone,Citizen,PRA,PRACountry,CurrentCollege,Major,ExpMonth,ExpDay,ExpYear,College1_College,College1_Dates,College1_Credits,College1_Major,College1_GPA,College2_College,College2_Dates,College2_Credits,College2_Major,College2_GPA,College3_College,College3_Dates,College3_Credits,College3_Major,College3_GPA,College4_College,College4_Dates,College4_Credits,College4_Major,College4_GPA,ResearchExperience,Honors,wp,spr,sas,cad,daq,DaqText,ProgLang,SpecialSkills,Preference,STExpierence,FrusProject,HowHeard,Accept"
            s-column="Name" b-tableformat="TRUE" b-hasHTML="FALSE" clientside
            local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
            preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Name")%><!--webbot
            bot="DatabaseResultColumn" endspan -->
                </td>
              </tr>
              <!--webbot bot="DatabaseRegionEnd" startspan b-tableformat="TRUE"
        b-menuformat="FALSE" u-dbrgn2="../../_fpclass/fpdbrgn2.inc"
        i-groupsize="25" clientside tag="TBODY"
        local_preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;TR&gt;&lt;TD ALIGN=LEFT VALIGN=MIDDLE COLSPAN=64&gt;&lt;FORM&gt;&lt;NOBR&gt;&lt;INPUT TYPE=Button VALUE=&quot;  |&lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;   &lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;   &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;|  &quot;&gt;  [1/25]&lt;/NOBR&gt;&lt;/FORM&gt;&lt;/td&gt;&lt;/tr&gt;"
        preview="&lt;tr&gt;&lt;td colspan=64 bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot; width=&quot;100%&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;TR&gt;&lt;TD ALIGN=LEFT VALIGN=MIDDLE COLSPAN=64&gt;&lt;NOBR&gt;&lt;INPUT TYPE=Button VALUE=&quot;  |&lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;   &lt;  &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;   &quot;&gt;&lt;INPUT TYPE=Button VALUE=&quot;  &gt;|  &quot;&gt;  [1/25]&lt;/NOBR&gt;&lt;BR&gt;&lt;/td&gt;&lt;/tr&gt;" --><!--#include file="../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan -->
            </tbody>
          </table>
          </center>
        </div>
        <p>&nbsp;
        </td>
      </tr>
      <tr>
        <td width="861" colspan="2" valign="middle" height="87">
          <br>
          <br>
          <br>
          <br>
        </td>
      </tr>
    </table>

    <p>&nbsp;</p>
    <p>&nbsp;</p>

  </body>

</html>
