<html>

<head>
<% ' FP_ASP -- ASP Automatically generated by a Frontpage Component. Do not Edit.
FP_CharSet = "windows-1252"
FP_CodePage = 1252 %>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Plasma Science and Fusion Energy Institute for High School Physics
Teachers Application Form Search</title>
</head>

<body>

<!--webbot bot="DatabaseRegionStart" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-columntypes="3,202,202,202,202,202,202,203,203,203,202,203,203,203,203,203,203,203,203,203,202,202,202,202,202,135,203,202,202"
s-dataconnection="PlasmaCamp" b-tableformat="FALSE" b-menuformat="FALSE"
s-menuchoice s-menuvalue b-tableborder="TRUE" b-tableexpand="TRUE"
b-tableheader="TRUE" b-listlabels="TRUE" b-listseparator="TRUE" i-ListFormat="0"
b-makeform="TRUE" s-recordsource="TeachersApplication2002"
s-displaycolumns="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-criteria s-order s-sql="SELECT * FROM TeachersApplication2002"
b-procedure="FALSE" clientside SuggestedExt="asp" s-DefaultFields
s-NoRecordsFound="No records returned." i-MaxRecords="5" i-GroupSize="0"
BOTID="0" u-dblib="../../../_fpclass/fpdblib.inc"
u-dbrgn1="../../../_fpclass/fpdbrgn1.inc"
u-dbrgn2="../../../_fpclass/fpdbrgn2.inc" tag="BODY"
local_preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;Database Results regions will not preview unless this page is fetched from a Web server using a web browser. The section of the page from here to the end of the Database Results region will repeat once for each record returned by the query.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;"
preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the start of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;" --><!--#include file="../../../_fpclass/fpdblib.inc"-->
<%
fp_sQry="SELECT * FROM TeachersApplication2002"
fp_sDefault=""
fp_sNoRecords="No records returned."
fp_sDataConn="PlasmaCamp"
fp_iMaxRecords=5
fp_iCommandType=1
fp_iPageSize=0
fp_fTableFormat=False
fp_fMenuFormat=False
fp_sMenuChoice=""
fp_sMenuValue=""
fp_iDisplayCols=29
fp_fCustomQuery=False
BOTID=0
fp_iRegion=BOTID
%>
<!--#include file="../../../_fpclass/fpdbrgn1.inc"-->
<!--webbot bot="DatabaseRegionStart" endspan -->
<p><b>ID:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="ID" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ID&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"ID")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>Name:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="Name" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Name&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Name")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>Address:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="Address" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Address&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Address&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Address")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>Phone:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="Phone" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Phone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Phone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Phone")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>eMail:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="eMail" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;eMail&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;eMail&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"eMail")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>SchoolPhone:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="SchoolPhone" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SchoolPhone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;SchoolPhone&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"SchoolPhone")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>PrincipalName:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="PrincipalName" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;PrincipalName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;PrincipalName&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"PrincipalName")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>CollegesAttended:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="CollegesAttended" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CollegesAttended&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CollegesAttended&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"CollegesAttended")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>UndergradCourses:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="UndergradCourses" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;UndergradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;UndergradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"UndergradCourses")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>GradCourses:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="GradCourses" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;GradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;GradCourses&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"GradCourses")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>YearsExp:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="YearsExp" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;YearsExp&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;YearsExp&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"YearsExp")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>TeachingAssign:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="TeachingAssign" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingAssign&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingAssign&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"TeachingAssign")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>FutureTeachings:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="FutureTeachings" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FutureTeachings&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;FutureTeachings&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"FutureTeachings")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>ProDev:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="ProDev" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ProDev&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;ProDev&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"ProDev")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>LeadershipActivities:</b>&nbsp;<!--webbot bot="DatabaseResultColumn"
startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="LeadershipActivities" b-tableformat="FALSE" b-hasHTML="FALSE"
clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LeadershipActivities&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;LeadershipActivities&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"LeadershipActivities")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>Publications:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="Publications" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Publications&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Publications&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Publications")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>TeachingPhilosophy:</b>&nbsp;<!--webbot bot="DatabaseResultColumn"
startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="TeachingPhilosophy" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingPhilosophy&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;TeachingPhilosophy&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"TeachingPhilosophy")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>EquiptExperience:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="EquiptExperience" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;EquiptExperience&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;EquiptExperience&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"EquiptExperience")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>CompExpierence:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="CompExpierence" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CompExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;CompExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"CompExpierence")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>IntExpierence:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="IntExpierence" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;IntExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;IntExpierence&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"IntExpierence")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>HowDidYouLearnAboutUs:</b>&nbsp;<!--webbot bot="DatabaseResultColumn"
startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="HowDidYouLearnAboutUs" b-tableformat="FALSE" b-hasHTML="FALSE"
clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;HowDidYouLearnAboutUs&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;HowDidYouLearnAboutUs&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"HowDidYouLearnAboutUs")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>Complete:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="Complete" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Complete&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Complete&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Complete")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>City:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="City" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;City&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;City&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"City")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>State:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="State" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;State&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;State&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"State")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>Zip:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="Zip" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Zip&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Zip&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Zip")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>Timestamp:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="Timestamp" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Timestamp&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Timestamp&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Timestamp")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>School2:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="School2" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;School2&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;School2&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"School2")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>Remote_computer_name1:</b>&nbsp;<!--webbot bot="DatabaseResultColumn"
startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="Remote_computer_name1" b-tableformat="FALSE" b-hasHTML="FALSE"
clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Remote_computer_name1&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Remote_computer_name1&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Remote_computer_name1")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<p><b>Browser_type1:</b>&nbsp;<!--webbot bot="DatabaseResultColumn" startspan
s-columnnames="ID,Name,Address,Phone,eMail,SchoolPhone,PrincipalName,CollegesAttended,UndergradCourses,GradCourses,YearsExp,TeachingAssign,FutureTeachings,ProDev,LeadershipActivities,Publications,TeachingPhilosophy,EquiptExperience,CompExpierence,IntExpierence,HowDidYouLearnAboutUs,Complete,City,State,Zip,Timestamp,School2,Remote_computer_name1,Browser_type1"
s-column="Browser_type1" b-tableformat="FALSE" b-hasHTML="FALSE" clientside
local_preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Browser_type1&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;"
preview="&lt;font size=&quot;-1&quot;&gt;&amp;lt;&amp;lt;&lt;/font&gt;Browser_type1&lt;font size=&quot;-1&quot;&gt;&amp;gt;&amp;gt;&lt;/font&gt;" --><%=FP_FieldVal(fp_rs,"Browser_type1")%><!--webbot
bot="DatabaseResultColumn" endspan -->
</p>
<hr>
<!--webbot bot="DatabaseRegionEnd" startspan b-tableformat="FALSE"
b-menuformat="FALSE" u-dbrgn2="../../../_fpclass/fpdbrgn2.inc" i-groupsize="0"
clientside tag="BODY"
local_preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;center&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;End of Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;"
preview="&lt;table border=0 width=&quot;100%&quot;&gt;&lt;tr&gt;&lt;td bgcolor=&quot;#FFFF00&quot; align=&quot;left&quot;&gt;&lt;font color=&quot;#000000&quot;&gt;This is the end of a Database Results region.&lt;/font&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;" --><!--#include file="../../../_fpclass/fpdbrgn2.inc"-->
<!--webbot bot="DatabaseRegionEnd" endspan -->

</body>

</html>
